// Generated from the frozen monolith by scripts/extract-legacy-static-data.mjs.
// Do not edit this file manually.

export const CLASSES = {
      Warrior: { hp: 160, mp: 40, atk: 18, def: 12, mpRegen: 2, skill: 'Taunt', skillMp: 10, skillEffect: 'taunt' },
      Cleric: { hp: 100, mp: 120, atk: 10, def: 8, mpRegen: 8, skill: 'Holy Bolt', skillMp: 20, skillEffect: 'holy' },
      Paladin: { hp: 145, mp: 90, atk: 15, def: 11, mpRegen: 5, skill: 'Holy Strike', skillMp: 18, skillEffect: 'holy' },
      Ranger: { hp: 130, mp: 90, atk: 16, def: 9, mpRegen: 5, skill: 'Hunter Volley', skillMp: 16, skillEffect: 'back' },
      'Death Knight': { hp: 145, mp: 95, atk: 15, def: 10, mpRegen: 5, skill: 'Unholy Blast', skillMp: 20, skillEffect: 'fire' },
      Druid: { hp: 95, mp: 135, atk: 11, def: 7, mpRegen: 9, skill: 'Nature Wrath', skillMp: 22, skillEffect: 'holy' },
      Monk: { hp: 130, mp: 55, atk: 19, def: 8, mpRegen: 4, skill: 'Flying Kick', skillMp: 14, skillEffect: 'back' },
      Bard: { hp: 120, mp: 100, atk: 13, def: 9, mpRegen: 7, skill: 'Discordant Note', skillMp: 17, skillEffect: 'holy' },
      Rogue: { hp: 110, mp: 80, atk: 22, def: 6, mpRegen: 5, skill: 'Backstab', skillMp: 15, skillEffect: 'back' },
      Shaman: { hp: 110, mp: 125, atk: 11, def: 8, mpRegen: 8, skill: 'Ancestral Bolt', skillMp: 20, skillEffect: 'holy' },
      Necromancer: { hp: 85, mp: 155, atk: 9, def: 5, mpRegen: 10, skill: 'Lifedraw', skillMp: 24, skillEffect: 'fire' },
      Wizard: { hp: 80, mp: 160, atk: 8, def: 4, mpRegen: 10, skill: 'Fireball', skillMp: 30, skillEffect: 'fire' },
      Conjurer: { hp: 90, mp: 150, atk: 9, def: 5, mpRegen: 10, skill: 'Arcane Burst', skillMp: 24, skillEffect: 'fire' },
      Enchanter: { hp: 85, mp: 145, atk: 9, def: 5, mpRegen: 11, skill: 'Mind Lance', skillMp: 22, skillEffect: 'holy' },
      Beastmaster: { hp: 125, mp: 95, atk: 17, def: 9, mpRegen: 6, skill: 'Savage Claw', skillMp: 16, skillEffect: 'back' },
      Berserker: { hp: 150, mp: 40, atk: 21, def: 8, mpRegen: 2, skill: 'Frenzied Axe', skillMp: 12, skillEffect: 'back' }
    } as const

export const ABILITIES = ['str', 'dex', 'con', 'int', 'wis', 'cha'] as const

export const ABILITY_LABELS = { str: 'STR', dex: 'DEX', con: 'CON', int: 'INT', wis: 'WIS', cha: 'CHA' } as const

export const ABILITY_FULL = {
      str: 'Strength', dex: 'Dexterity', con: 'Constitution',
      int: 'Intelligence', wis: 'Wisdom', cha: 'Charisma'
    } as const

export const ABILITY_EFFECT_TEXT = {
      str: '+attack power', dex: '+crit & dodge', con: 'damage reduction',
      int: '+spell damage', wis: '+mana regen', cha: '+gold find'
    } as const

export const CLASS_ABILITIES = {
      Warrior: { str: 15, dex: 12, con: 14, int: 8, wis: 10, cha: 9 },
      Cleric: { str: 11, dex: 9, con: 12, int: 10, wis: 15, cha: 12 },
      Paladin: { str: 14, dex: 9, con: 13, int: 8, wis: 11, cha: 13 },
      Ranger: { str: 12, dex: 15, con: 12, int: 10, wis: 13, cha: 8 },
      'Death Knight': { str: 14, dex: 10, con: 13, int: 11, wis: 9, cha: 12 },
      Druid: { str: 10, dex: 11, con: 12, int: 13, wis: 15, cha: 10 },
      Monk: { str: 13, dex: 15, con: 13, int: 9, wis: 13, cha: 8 },
      Bard: { str: 9, dex: 13, con: 10, int: 12, wis: 11, cha: 15 },
      Rogue: { str: 11, dex: 15, con: 11, int: 12, wis: 9, cha: 12 },
      Shaman: { str: 10, dex: 10, con: 12, int: 12, wis: 15, cha: 11 },
      Necromancer: { str: 8, dex: 10, con: 11, int: 15, wis: 13, cha: 10 },
      Wizard: { str: 8, dex: 11, con: 10, int: 15, wis: 13, cha: 10 },
      Conjurer: { str: 8, dex: 10, con: 10, int: 15, wis: 13, cha: 11 },
      Enchanter: { str: 8, dex: 11, con: 10, int: 14, wis: 12, cha: 15 },
      Beastmaster: { str: 13, dex: 13, con: 12, int: 9, wis: 12, cha: 11 },
      Berserker: { str: 15, dex: 12, con: 14, int: 8, wis: 8, cha: 9 }
    } as const

export const ABILITY_GROWTH_EVERY = 4 as const

export const CLASS_ICONS = {
      Warrior: 'ti-shield', Cleric: 'ti-heart', Paladin: 'ti-shield-check', Ranger: 'ti-bow', 'Death Knight': 'ti-moon-stars',
      Druid: 'ti-leaf', Monk: 'ti-karate', Bard: 'ti-music', Rogue: 'ti-knife', Shaman: 'ti-bolt', Necromancer: 'ti-skull',
      Wizard: 'ti-wand', Conjurer: 'ti-sparkles', Enchanter: 'ti-stars', Beastmaster: 'ti-paw', Berserker: 'ti-axe'
    } as const

export const CLASS_COLORS = {
      Warrior: '#E24B4A', Cleric: '#1D9E75', Paladin: '#3B8AC4', Ranger: '#548A37', 'Death Knight': '#5A4A8A', Druid: '#4E9A55',
      Monk: '#A66E3A', Bard: '#9A6B35', Rogue: '#BA7517', Shaman: '#2B8B84', Necromancer: '#7A4A9F', Wizard: '#7F77DD',
      Conjurer: '#5D73C7', Enchanter: '#C067C0', Beastmaster: '#8A7445', Berserker: '#C25050'
    } as const

export const CLASS_DESCRIPTIONS = {
      Warrior: 'Frontline tank and weapon master.',
      Cleric: 'Divine healer and protector.',
      Paladin: 'Holy knight with support magic.',
      Ranger: 'Hybrid archer with survival skills.',
      'Death Knight': 'Dark knight using unholy power.',
      Druid: 'Nature caster with healing utility.',
      Monk: 'Fast martial striker and puller.',
      Bard: 'Songs and utility in every fight.',
      Rogue: 'Stealth burst damage specialist.',
      Shaman: 'Totemic caster with buffs and debuffs.',
      Necromancer: 'Dark caster using life and decay.',
      Wizard: 'Pure arcane burst damage caster.',
      Conjurer: 'Elemental summoner and nuker.',
      Enchanter: 'Control and mana manipulation caster.',
      Beastmaster: 'Savage hybrid fighter and mystic.',
      Berserker: 'Frenzied melee damage dealer.'
    } as const

export const GAME_RACES = ['Human', 'Goliath', 'Aasimar', 'Wood Elf', 'High Elf', 'Dark Elf', 'Half Elf', 'Dwarf', 'Troll', 'Ogre', 'Halfling', 'Gnome', 'Lizardfolk', 'Tabaxi', 'Bullywug', 'Dragonborn'] as const

export const RACE_ICONS = {
      Human: 'ti-user', Goliath: 'ti-helmet', Aasimar: 'ti-scroll-text', 'Wood Elf': 'ti-tree', 'High Elf': 'ti-sparkles',
      'Dark Elf': 'ti-moon', 'Half Elf': 'ti-adjustments', Dwarf: 'ti-hammer', Troll: 'ti-skull', Ogre: 'ti-shield-half',
      Halfling: 'ti-chef-hat', Gnome: 'ti-bulb', Lizardfolk: 'ti-dna-2', 'Tabaxi': 'ti-cat', Bullywug: 'ti-droplet', Dragonborn: 'ti-flame'
    } as const

export const RACE_CLASS_RULES = {
      Human: ['Warrior', 'Cleric', 'Paladin', 'Ranger', 'Death Knight', 'Druid', 'Monk', 'Bard', 'Rogue', 'Necromancer', 'Wizard', 'Conjurer', 'Enchanter'],
      Goliath: ['Warrior', 'Rogue', 'Shaman', 'Beastmaster', 'Berserker'],
      Aasimar: ['Cleric', 'Paladin', 'Death Knight', 'Necromancer', 'Wizard', 'Conjurer', 'Enchanter'],
      'Wood Elf': ['Warrior', 'Ranger', 'Druid', 'Bard', 'Rogue'],
      'High Elf': ['Cleric', 'Paladin', 'Wizard', 'Conjurer', 'Enchanter'],
      'Dark Elf': ['Warrior', 'Cleric', 'Death Knight', 'Rogue', 'Necromancer', 'Wizard', 'Conjurer', 'Enchanter'],
      'Half Elf': ['Warrior', 'Paladin', 'Ranger', 'Druid', 'Bard', 'Rogue'],
      Dwarf: ['Warrior', 'Cleric', 'Paladin', 'Rogue', 'Berserker'],
      Troll: ['Warrior', 'Death Knight', 'Shaman', 'Beastmaster', 'Berserker'],
      Ogre: ['Warrior', 'Death Knight', 'Shaman', 'Beastmaster', 'Berserker'],
      Halfling: ['Warrior', 'Cleric', 'Druid', 'Rogue'],
      Gnome: ['Warrior', 'Cleric', 'Rogue', 'Necromancer', 'Wizard', 'Conjurer', 'Enchanter'],
      Lizardfolk: ['Warrior', 'Monk', 'Death Knight', 'Shaman', 'Necromancer', 'Beastmaster', 'Berserker'],
      'Tabaxi': ['Warrior', 'Monk', 'Bard', 'Rogue', 'Beastmaster', 'Berserker'],
      Bullywug: ['Warrior', 'Cleric', 'Paladin', 'Death Knight', 'Monk', 'Rogue', 'Wizard', 'Enchanter'],
      Dragonborn: ['Warrior', 'Cleric', 'Paladin', 'Ranger', 'Death Knight', 'Druid', 'Monk', 'Bard', 'Rogue', 'Shaman', 'Necromancer', 'Wizard', 'Conjurer', 'Enchanter', 'Beastmaster', 'Berserker']
    } as const
