// Generated from the frozen monolith by scripts/extract-legacy-static-data.mjs.
// Do not edit this file manually.

export const PHASE1 = {
      gcdMs: 800,
      playerCrit: 0.05,
      playerCritMult: 1.6,
      playerDodge: 0.04,
      mobCrit: 0.04,
      mobCritMult: 1.5,
      mobDodgeBase: 0.03,
      eliteCritBonus: 0.03,
      namedCritBonus: 0.06,
      mercTankAbsorbChance: 0.18,
      mercTankAbsorbMin: 0.30,
      mercTankAbsorbMax: 0.50,
      stunOnCritChance: 0.10,
      stunDurationMs: 1500,
      poisonDotDps: 4,
      poisonDotDurationMs: 12000
    } as const

export const PHASE2 = {
      legendaryChanceNamed: 0.025,
      legendaryChanceRegular: 0.0015,
      legendaryAffixCount: 3,
      legendaryStatBoost: { atk: 3, def: 3, hp: 16, mp: 16 },
      mythicChanceNamed: 0.006,
      mythicChanceRegular: 0.0003,
      mythicAffixCount: 4,
      mythicStatBoost: { atk: 6, def: 6, hp: 30, mp: 30 },
      levelReqOffset: 2,
      overflowSoftCap: 20
    } as const

export const PHASE4 = {
      bossCooldownMs: 30 * 60 * 1000, 
      bossHpMult: 6,
      bossAtkMult: 2.2,
      bossDefMult: 1.8,
      bossXpMult: 5,
      bossGoldMult: 4,
      bossLegendaryChance: 0.18, 
      dailyResetMs: 24 * 60 * 60 * 1000,
      dailyQuestCount: 3,
      dailyXpMult: 2.0,
      dailyGoldMult: 2.0,
      hardcoreXpBonus: 0.25,
      hardcoreGoldBonus: 0.25
    } as const

export const PHASE6 = {
      zoneLevelFloor: true,
      zoneRangeAbovePlayer: 2,
      highLevelHpScale: 0.012,
      tributeBaseGold: 2500,
      tributeGoldPerLevel: 350,
      tributeFactionPerDonation: 1,
      tributeDailyCap: 25,
      tributeFactionMax: 200
    } as const

export const GOLD_DROP_MULT = 0.4 as const
