// Generated from the frozen monolith by scripts/extract-legacy-static-data.mjs.
// Do not edit this file manually.

export const ITEM_DATA = {
      'Rusty Dagger': { slot: 'weapon', atk: 4, type: 'Piercing Weapon' },
      'Worn Shortsword': { slot: 'weapon', atk: 7, type: 'Sword' },
      'Cracked Staff': { slot: 'weapon', atk: 5, mp: 20, type: 'Staff' },
      'Bronze Hatchet': { slot: 'weapon', atk: 6, type: 'Axe' },
      'Ashen Longbow': { slot: 'weapon', atk: 9, type: 'Bow' },
      'Runed Mace': { slot: 'weapon', atk: 11, mp: 18, type: 'Mace' },
      'Glacite Spear': { slot: 'weapon', atk: 14, type: 'Polearm' },

      'Tattered Robe': { slot: 'chest', def: 3, mp: 10, type: 'Cloth Armor' },
      'Studded Jerkin': { slot: 'chest', def: 6, hp: 24, type: 'Leather Armor' },
      'Scaled Cuirass': { slot: 'chest', def: 11, hp: 42, type: 'Scale Armor' },
      'Frostwoven Mantle': { slot: 'chest', def: 9, mp: 36, type: 'Mystic Armor' },
      'Ghoul-Touched Cloak': { slot: 'chest', def: 8, hp: 30, type: 'Rare Cloak' },
      'Hate Infused Plate': { slot: 'chest', def: 15, hp: 60, type: 'Plate Armor' },
      'Knight Chestplate': { slot: 'chest', def: 18, hp: 80, type: 'Plate Armor' },

      'Patchwork Leggings': { slot: 'legs', def: 4, hp: 14, type: 'Cloth Leggings' },
      'Chain Legguards': { slot: 'legs', def: 8, hp: 28, type: 'Chain Legguards' },
      'Runed Greaves': { slot: 'legs', def: 12, hp: 40, mp: 12, type: 'Runed Greaves' },

      'Rawhide Boots': { slot: 'feet', def: 2, hp: 10, type: 'Leather Boots' },
      'Traveler Sandals': { slot: 'feet', def: 3, mp: 8, type: 'Sandals' },
      'Iron Sabatons': { slot: 'feet', def: 7, hp: 22, type: 'Plate Boots' },
      'Glacier Treads': { slot: 'feet', def: 10, hp: 34, type: 'Frost Boots' },

      'Dread Quill': { slot: 'offhand', mp: 35, atk: 3, type: 'Focus Item' },
      'Bone Ward Totem': { slot: 'offhand', def: 5, hp: 18, type: 'Totem' },
      'Mirror Shield': { slot: 'offhand', def: 9, hp: 26, type: 'Shield' },
      'Storm Orb': { slot: 'offhand', atk: 5, mp: 40, type: 'Orb' },

      'Gnoll Fang Earring': { slot: 'charm', atk: 2, def: 2, type: 'Charm' },
      'Ember Sigil': { slot: 'charm', atk: 3, hp: 12, type: 'Charm' },
      'Warden Idol': { slot: 'charm', def: 4, hp: 20, type: 'Charm' },
      'Astral Loop': { slot: 'charm', mp: 28, atk: 2, type: 'Charm' },

      'Steel Longsword': { slot: 'weapon', atk: 12, type: 'Sword' }
    } as const

export const ITEM_DATA_EXPANSION = {
      'Hunter Spear':       { slot: 'weapon', atk: 13, type: 'Polearm' },
      'Warded Warblade':    { slot: 'weapon', atk: 14, def: 2, type: 'Sword' },
      'Obsidian Cleaver':   { slot: 'weapon', atk: 16, type: 'Axe' },
      'Stormcaller Staff':  { slot: 'weapon', atk: 13, mp: 40, type: 'Staff' },
      'Wyrmbone Greatbow':  { slot: 'weapon', atk: 17, type: 'Bow' },
      'Dread Halberd':      { slot: 'weapon', atk: 18, hp: 20, type: 'Polearm' },
      'Runescribed Maul':   { slot: 'weapon', atk: 19, mp: 30, type: 'Mace' },
      'Tempest Glaive':     { slot: 'weapon', atk: 20, type: 'Polearm' },
      'Ashen Warbrand':     { slot: 'weapon', atk: 21, def: 4, type: 'Sword' },
      'Voidpiercer Lance':  { slot: 'weapon', atk: 23, type: 'Polearm' },
      'Godshard Edge':      { slot: 'weapon', atk: 25, hp: 30, type: 'Sword' },
      'Worldspine Reaver':  { slot: 'weapon', atk: 27, type: 'Polearm' },
      'Veilrender Scythe':  { slot: 'weapon', atk: 30, def: 6, type: 'Scythe' },
      'Ironscale Hauberk':  { slot: 'chest', def: 19, hp: 70, type: 'Scale Armor' },
      'Warden Plate':       { slot: 'chest', def: 22, hp: 90, type: 'Plate Armor' },
      'Stormforged Cuirass':{ slot: 'chest', def: 25, hp: 105, mp: 24, type: 'Plate Armor' },
      'Dragonbone Carapace':{ slot: 'chest', def: 28, hp: 125, type: 'Dragonscale Armor' },
      'Godshard Plate':     { slot: 'chest', def: 32, hp: 150, type: 'Plate Armor' },
      'Worldspine Aegis':   { slot: 'chest', def: 38, hp: 185, type: 'Titanplate Armor' },
      'Ironscale Greaves':  { slot: 'legs', def: 14, hp: 48, type: 'Scale Legguards' },
      'Warden Legplates':   { slot: 'legs', def: 16, hp: 62, type: 'Plate Legguards' },
      'Stormforged Tassets':{ slot: 'legs', def: 19, hp: 78, mp: 18, type: 'Plate Legguards' },
      'Dragonbone Legguards':{ slot: 'legs', def: 22, hp: 95, type: 'Dragonscale Legguards' },
      'Godshard Legplates': { slot: 'legs', def: 26, hp: 118, type: 'Plate Legguards' },
      'Ironshod Greaves':   { slot: 'feet', def: 12, hp: 42, type: 'Plate Boots' },
      'Warden Sabatons':    { slot: 'feet', def: 14, hp: 56, type: 'Plate Boots' },
      'Stormstride Boots':  { slot: 'feet', def: 16, hp: 70, mp: 16, type: 'Plate Boots' },
      'Dragonbone Treads':  { slot: 'feet', def: 19, hp: 88, type: 'Dragonscale Boots' },
      'Godshard Striders':  { slot: 'feet', def: 23, hp: 108, type: 'Plate Boots' },
      'Tower Shield':       { slot: 'offhand', def: 14, hp: 50, type: 'Shield' },
      'Aether Codex':       { slot: 'offhand', atk: 7, mp: 60, type: 'Tome' },
      'Bulwark Shield':     { slot: 'offhand', def: 17, hp: 66, type: 'Shield' },
      'Tempest Sigil':      { slot: 'offhand', atk: 9, mp: 80, type: 'Focus Item' },
      'Dragonbone Bulwark': { slot: 'offhand', def: 21, hp: 84, type: 'Dragonscale Shield' },
      'Godshard Ward':      { slot: 'offhand', def: 26, hp: 105, mp: 40, type: 'Aegis' },
      'Bloodforged Charm':  { slot: 'charm', atk: 5, hp: 26, type: 'Charm' },
      'Wardstone Amulet':   { slot: 'charm', def: 6, hp: 34, type: 'Charm' },
      'Arcane Lodestone':   { slot: 'charm', atk: 4, mp: 50, type: 'Charm' },
      'Godshard Talisman':  { slot: 'charm', atk: 7, def: 7, hp: 50, type: 'Charm' }
    } as const

export const WEAPON_PROCS = {
      'Rusty Dagger': { name: 'Jagged Wound', chance: 0.12, type: 'poison', min: 4, max: 9 },
      'Worn Shortsword': { name: 'Sundering Slash', chance: 0.1, type: 'damage', min: 6, max: 12, weaken: 1 },
      'Cracked Staff': { name: 'Mana Surge', chance: 0.12, type: 'mana', min: 10, max: 20 },
      'Bronze Hatchet': { name: 'Rending Chop', chance: 0.11, type: 'damage', min: 7, max: 14, weaken: 1 },
      'Ashen Longbow': { name: 'Kindled Volley', chance: 0.1, type: 'poison', min: 8, max: 15 },
      'Runed Mace': { name: 'Glyph Burst', chance: 0.12, type: 'mana', min: 12, max: 24 },
      'Glacite Spear': { name: 'Piercing Gale', chance: 0.13, type: 'damage', min: 11, max: 20, weaken: 2 },
      'Steel Longsword': { name: 'Steel Tempest', chance: 0.14, type: 'damage', min: 12, max: 22, weaken: 2 }
    } as const

export const ITEM_SETS = {
      'Crypt Stalker': {
        pieces: ['Worn Shortsword', 'Rawhide Boots', 'Gnoll Fang Earring'],
        bonus2: { atk: 3, def: 1, procChance: 0.02 }
      },
      'Ember Warden': {
        pieces: ['Steel Longsword', 'Knight Chestplate', 'Dread Quill'],
        bonus2: { atk: 4, def: 2, procChance: 0.03 }
      },
      'Twilight Scholar': {
        pieces: ['Cracked Staff', 'Tattered Robe', 'Dread Quill'],
        bonus2: { atk: 2, def: 2, procChance: 0.02 }
      },
      'Wild Hunter': {
        pieces: ['Ashen Longbow', 'Studded Jerkin', 'Traveler Sandals'],
        bonus2: { atk: 3, def: 2, procChance: 0.02 }
      },
      'Storm Vanguard': {
        pieces: ['Glacite Spear', 'Runed Greaves', 'Mirror Shield'],
        bonus2: { atk: 4, def: 3, procChance: 0.03 }
      },
      'Ashen Seer': {
        pieces: ['Runed Mace', 'Frostwoven Mantle', 'Astral Loop'],
        bonus2: { atk: 3, def: 2, procChance: 0.03 }
      },
      'Dragonbone Warden': {
        pieces: ['Dragonbone Carapace', 'Dragonbone Legguards', 'Dragonbone Treads', 'Dragonbone Bulwark'],
        bonus2: { atk: 6, def: 14, procChance: 0.03 },
        bonus3: { atk: 14, def: 30, procChance: 0.05 }
      },
      'Tempest Regalia': {
        pieces: ['Tempest Glaive', 'Stormforged Cuirass', 'Stormstride Boots', 'Tempest Sigil'],
        bonus2: { atk: 14, def: 6, procChance: 0.04 },
        bonus3: { atk: 30, def: 14, procChance: 0.06 }
      },
      'Fallen God': {
        pieces: ['Godshard Edge', 'Godshard Plate', 'Godshard Legplates', 'Godshard Ward', 'Godshard Talisman'],
        bonus2: { atk: 18, def: 18, procChance: 0.04 },
        bonus3: { atk: 44, def: 44, procChance: 0.08 }
      }
    } as const

export const LOOT = [
      'Rusty Dagger', 'Worn Shortsword', 'Cracked Staff', 'Bronze Hatchet', 'Ashen Longbow',
      'Tattered Robe', 'Studded Jerkin', 'Patchwork Leggings', 'Rawhide Boots', 'Traveler Sandals',
      'Gnoll Fang Earring', 'Ember Sigil', 'Bone Ward Totem',
      'Steel Longsword', 'Knight Chestplate', 'Chain Legguards', 'Iron Sabatons', 'Mirror Shield', 'Warden Idol',
      'Runed Mace', 'Glacite Spear', 'Scaled Cuirass', 'Frostwoven Mantle', 'Runed Greaves', 'Glacier Treads', 'Storm Orb', 'Astral Loop',
      'Ghoul-Touched Cloak', 'Hate Infused Plate', 'Dread Quill',
      'Bone Chip', 'Animal Pelt', 'Orc Tooth', 'Spider Silk', 'Giant Snake Fang', 'Mithril Ingot',
      'Hunter Spear', 'Warded Warblade', 'Obsidian Cleaver', 'Stormcaller Staff', 'Wyrmbone Greatbow',
      'Dread Halberd', 'Runescribed Maul', 'Tempest Glaive', 'Ashen Warbrand', 'Voidpiercer Lance',
      'Godshard Edge', 'Worldspine Reaver', 'Veilrender Scythe',
      'Ironscale Hauberk', 'Warden Plate', 'Stormforged Cuirass', 'Dragonbone Carapace', 'Godshard Plate', 'Worldspine Aegis',
      'Ironscale Greaves', 'Warden Legplates', 'Stormforged Tassets', 'Dragonbone Legguards', 'Godshard Legplates',
      'Ironshod Greaves', 'Warden Sabatons', 'Stormstride Boots', 'Dragonbone Treads', 'Godshard Striders',
      'Tower Shield', 'Aether Codex', 'Bulwark Shield', 'Tempest Sigil', 'Dragonbone Bulwark', 'Godshard Ward',
      'Bloodforged Charm', 'Wardstone Amulet', 'Arcane Lodestone', 'Godshard Talisman'
    ] as const

export const LOOT_TIER_STARTER = [
      'Rusty Dagger', 'Worn Shortsword', 'Cracked Staff', 'Bronze Hatchet',
      'Tattered Robe', 'Studded Jerkin', 'Patchwork Leggings', 'Rawhide Boots', 'Traveler Sandals',
      'Gnoll Fang Earring', 'Ember Sigil', 'Bone Ward Totem'
    ] as const

export const LOOT_TIER_MID = [
      'Ashen Longbow', 'Steel Longsword', 'Runed Mace', 'Hunter Spear', 'Warded Warblade',
      'Scaled Cuirass', 'Ghoul-Touched Cloak', 'Chain Legguards', 'Iron Sabatons', 'Ironscale Hauberk', 'Ironscale Greaves', 'Ironshod Greaves',
      'Dread Quill', 'Mirror Shield', 'Warden Idol', 'Astral Loop', 'Tower Shield', 'Bloodforged Charm', 'Wardstone Amulet'
    ] as const

export const LOOT_TIER_ADVANCED = [
      'Glacite Spear', 'Knight Chestplate', 'Hate Infused Plate', 'Frostwoven Mantle',
      'Runed Greaves', 'Glacier Treads', 'Storm Orb',
      'Obsidian Cleaver', 'Stormcaller Staff', 'Wyrmbone Greatbow', 'Dread Halberd',
      'Warden Plate', 'Warden Legplates', 'Warden Sabatons', 'Aether Codex', 'Bulwark Shield', 'Arcane Lodestone'
    ] as const

export const LOOT_TIER_EPIC = [
      'Runescribed Maul', 'Tempest Glaive', 'Ashen Warbrand', 'Voidpiercer Lance',
      'Stormforged Cuirass', 'Dragonbone Carapace', 'Stormforged Tassets', 'Dragonbone Legguards',
      'Stormstride Boots', 'Dragonbone Treads', 'Tempest Sigil', 'Dragonbone Bulwark', 'Godshard Talisman'
    ] as const

export const LOOT_TIER_MYTHIC = [
      'Godshard Edge', 'Worldspine Reaver', 'Veilrender Scythe',
      'Godshard Plate', 'Worldspine Aegis', 'Godshard Legplates', 'Godshard Striders', 'Godshard Ward'
    ] as const

export const LOOT_MISC_BASES = ['Bone Chip', 'Animal Pelt', 'Orc Tooth', 'Spider Silk', 'Giant Snake Fang', 'Mithril Ingot'] as const

export const ITEM_AFFIX_POOL = {
      weapon: [
        { stat: 'atk', min: 1, max: 5, prefix: 'Jagged', suffix: 'Slaying' },
        { stat: 'atk', min: 2, max: 7, prefix: 'Brutal', suffix: 'Carnage' },
        { stat: 'mp',  min: 6, max: 24, prefix: 'Mystic', suffix: 'Focus' },
        { stat: 'str', min: 1, max: 3, prefix: 'Mighty',  suffix: 'the Bull' },
        { stat: 'dex', min: 1, max: 3, prefix: 'Agile',   suffix: 'the Fox' },
        { stat: 'con', min: 1, max: 3, prefix: 'Ironhide', suffix: 'Endurance' },
        { stat: 'int', min: 1, max: 3, prefix: 'Runic',   suffix: 'the Scholar' },
        { stat: 'wis', min: 1, max: 3, prefix: 'Tempered', suffix: 'the Sage' },
        { stat: 'cha', min: 1, max: 3, prefix: 'Radiant', suffix: 'Allure' }
      ],
      chest: [
        { stat: 'def', min: 1, max: 5, prefix: 'Sturdy',    suffix: 'the Bear' },
        { stat: 'hp',  min: 10, max: 38, prefix: 'Vigorous', suffix: 'Vitality' },
        { stat: 'mp',  min: 8, max: 28, prefix: 'Runed',    suffix: 'the Sage' },
        { stat: 'con', min: 1, max: 3, prefix: 'Stalwart',  suffix: 'the Ox' },
        { stat: 'str', min: 1, max: 3, prefix: 'Ironclad',  suffix: 'the Titan' },
        { stat: 'dex', min: 1, max: 2, prefix: 'Lithe',     suffix: 'the Viper' },
        { stat: 'int', min: 1, max: 2, prefix: 'Glyphed',   suffix: 'Sorcery' },
        { stat: 'wis', min: 1, max: 2, prefix: 'Blessed',   suffix: 'the Monk' },
        { stat: 'cha', min: 1, max: 2, prefix: 'Gilded',    suffix: 'Nobility' }
      ],
      legs: [
        { stat: 'def', min: 1, max: 4, prefix: 'Guarded',   suffix: 'Warding' },
        { stat: 'hp',  min: 8, max: 30, prefix: 'Hardened', suffix: 'Fortitude' },
        { stat: 'con', min: 1, max: 2, prefix: 'Tough',     suffix: 'the Boar' },
        { stat: 'str', min: 1, max: 2, prefix: 'Striding',  suffix: 'the Colossus' },
        { stat: 'dex', min: 1, max: 2, prefix: 'Fleet',     suffix: 'the Wind' },
        { stat: 'int', min: 1, max: 2, prefix: 'Mystweave', suffix: 'Wisdom' },
        { stat: 'wis', min: 1, max: 2, prefix: 'Meditative', suffix: 'the Hermit' },
        { stat: 'cha', min: 1, max: 2, prefix: 'Regal',     suffix: 'Prestige' }
      ],
      feet: [
        { stat: 'def', min: 1, max: 3, prefix: 'Surefooted', suffix: 'Balance' },
        { stat: 'hp',  min: 6, max: 20, prefix: 'Stout',     suffix: 'Endurance' },
        { stat: 'dex', min: 1, max: 2, prefix: 'Swift',      suffix: 'the Hare' },
        { stat: 'str', min: 1, max: 2, prefix: 'Stomping',   suffix: 'the Giant' },
        { stat: 'con', min: 1, max: 2, prefix: 'Grounded',   suffix: 'the Rock' },
        { stat: 'int', min: 1, max: 2, prefix: 'Arcane',     suffix: 'Wayfaring' },
        { stat: 'wis', min: 1, max: 2, prefix: "Wanderer's", suffix: 'Insight' },
        { stat: 'cha', min: 1, max: 2, prefix: 'Graceful',   suffix: 'the Noble' }
      ],
      offhand: [
        { stat: 'atk', min: 1, max: 3, prefix: 'Keen',       suffix: 'Precision' },
        { stat: 'mp',  min: 8, max: 26, prefix: 'Arcane',    suffix: 'Insight' },
        { stat: 'def', min: 1, max: 3, prefix: 'Warded',     suffix: 'Protection' },
        { stat: 'int', min: 1, max: 3, prefix: 'Clever',     suffix: 'the Owl' },
        { stat: 'wis', min: 1, max: 3, prefix: 'Wise',       suffix: 'the Oracle' },
        { stat: 'str', min: 1, max: 2, prefix: 'Bolstering', suffix: 'the Strong' },
        { stat: 'dex', min: 1, max: 2, prefix: 'Nimble',     suffix: 'the Quick' },
        { stat: 'con', min: 1, max: 2, prefix: 'Fortifying', suffix: 'the Steadfast' },
        { stat: 'cha', min: 1, max: 2, prefix: 'Inspiring',  suffix: 'the Leader' }
      ],
      charm: [
        { stat: 'atk', min: 1, max: 2, prefix: 'Savage',      suffix: 'Striking' },
        { stat: 'def', min: 1, max: 2, prefix: 'Blessed',     suffix: 'Guarding' },
        { stat: 'hp',  min: 6, max: 20, prefix: 'Hearty',     suffix: 'Life' },
        { stat: 'mp',  min: 6, max: 20, prefix: 'Sage',       suffix: 'Mana' },
        { stat: 'cha', min: 1, max: 3, prefix: 'Charming',    suffix: 'Allure' },
        { stat: 'wis', min: 1, max: 2, prefix: 'Insightful',  suffix: 'the Mind' },
        { stat: 'str', min: 1, max: 2, prefix: 'Emboldening', suffix: 'Might' },
        { stat: 'dex', min: 1, max: 2, prefix: 'Flickering',  suffix: 'Swiftness' },
        { stat: 'con', min: 1, max: 2, prefix: 'Enduring',    suffix: 'Resilience' },
        { stat: 'int', min: 1, max: 2, prefix: 'Brilliant',   suffix: 'the Arcane' }
      ]
    } as const

export const EPIC_ITEM_BY_BASE = {
      'Rusty Dagger': [
        { id: 'bloodletter_shiv', name: 'Bloodletter Shiv', rolls: { atk: 10, hp: 24 } }
      ],
      'Worn Shortsword': [
        { id: 'old_kings_blade', name: "Old King's Blade", rolls: { atk: 13, def: 4 } }
      ],
      'Cracked Staff': [
        { id: 'stormspine', name: 'Stormspine', rolls: { atk: 6, mp: 44 } }
      ],
      'Bronze Hatchet': [
        { id: 'briarcleaver', name: 'Briarcleaver', rolls: { atk: 12, hp: 18 } }
      ],
      'Ashen Longbow': [
        { id: 'embersight', name: 'Embersight', rolls: { atk: 14, mp: 20 } }
      ],
      'Runed Mace': [
        { id: 'glyphbreaker', name: 'Glyphbreaker', rolls: { atk: 13, mp: 34 } }
      ],
      'Glacite Spear': [
        { id: 'icethorn_pike', name: 'Icethorn Pike', rolls: { atk: 18, def: 5 } }
      ],
      'Tattered Robe': [
        { id: 'veil_of_ashes', name: 'Veil of Ashes', rolls: { def: 7, mp: 42 } }
      ],
      'Studded Jerkin': [
        { id: 'wolfhide_harness', name: 'Wolfhide Harness', rolls: { def: 9, hp: 34 } }
      ],
      'Scaled Cuirass': [
        { id: 'basilisk_carapace', name: 'Basilisk Carapace', rolls: { def: 12, hp: 48 } }
      ],
      'Frostwoven Mantle': [
        { id: 'winterveil', name: 'Winterveil', rolls: { def: 10, mp: 50 } }
      ],
      'Rawhide Boots': [
        { id: 'duststep', name: 'Duststep', rolls: { def: 5, hp: 30 } }
      ],
      'Patchwork Leggings': [
        { id: 'trailbound_wraps', name: 'Trailbound Wraps', rolls: { def: 7, hp: 28 } }
      ],
      'Chain Legguards': [
        { id: 'vanguard_legplates', name: 'Vanguard Legplates', rolls: { def: 11, hp: 36 } }
      ],
      'Runed Greaves': [
        { id: 'sigil_treads', name: 'Sigil Treads', rolls: { def: 14, hp: 44, mp: 18 } }
      ],
      'Traveler Sandals': [
        { id: 'wayfarer_step', name: 'Wayfarer Step', rolls: { def: 6, mp: 20 } }
      ],
      'Iron Sabatons': [
        { id: 'dreadmarch_boots', name: 'Dreadmarch Boots', rolls: { def: 10, hp: 34 } }
      ],
      'Glacier Treads': [
        { id: 'frozen_stride', name: 'Frozen Stride', rolls: { def: 12, hp: 44 } }
      ],
      'Gnoll Fang Earring': [
        { id: 'packlords_trophy', name: "Packlord's Trophy", rolls: { atk: 4, def: 4, hp: 22 } }
      ],
      'Ember Sigil': [
        { id: 'emberheart_seal', name: 'Emberheart Seal', rolls: { atk: 5, hp: 26 } }
      ],
      'Warden Idol': [
        { id: 'idol_of_oaks', name: 'Idol of Oaks', rolls: { def: 6, hp: 34 } }
      ],
      'Astral Loop': [
        { id: 'starlit_band', name: 'Starlit Band', rolls: { atk: 4, mp: 40 } }
      ],
      'Dread Quill': [
        { id: 'quill_of_fear', name: 'Quill of Fear', rolls: { atk: 7, mp: 50 } }
      ],
      'Bone Ward Totem': [
        { id: 'totem_of_laments', name: 'Totem of Laments', rolls: { def: 7, hp: 30 } }
      ],
      'Mirror Shield': [
        { id: 'aegis_of_reflection', name: 'Aegis of Reflection', rolls: { def: 12, hp: 38 } }
      ],
      'Storm Orb': [
        { id: 'stormcore', name: 'Stormcore', rolls: { atk: 8, mp: 56 } }
      ],
      'Steel Longsword': [
        { id: 'oathcleaver', name: 'Oathcleaver', rolls: { atk: 16, hp: 30 } }
      ],
      'Knight Chestplate': [
        { id: 'bulwark_of_ember', name: 'Bulwark of Ember', rolls: { def: 12, hp: 48 } }
      ],
      'Hunter Spear': [ { id: 'wolfmaw_pike', name: 'Wolfmaw Pike', rolls: { atk: 16, hp: 22 } } ],
      'Warded Warblade': [ { id: 'oathwarden', name: 'Oathwarden', rolls: { atk: 17, def: 6 } } ],
      'Obsidian Cleaver': [ { id: 'nightfall_cleaver', name: 'Nightfall Cleaver', rolls: { atk: 20, hp: 28 } } ],
      'Stormcaller Staff': [ { id: 'tempest_branch', name: 'Tempest Branch', rolls: { atk: 16, mp: 56 } } ],
      'Wyrmbone Greatbow': [ { id: 'dragonsong_bow', name: 'Dragonsong Bow', rolls: { atk: 22, mp: 22 } } ],
      'Dread Halberd': [ { id: 'gravemaker', name: 'Gravemaker', rolls: { atk: 23, hp: 36 } } ],
      'Runescribed Maul': [ { id: 'glyphshatter_maul', name: 'Glyphshatter Maul', rolls: { atk: 24, mp: 48 } } ],
      'Tempest Glaive': [ { id: 'skyrender_glaive', name: 'Skyrender Glaive', rolls: { atk: 26, def: 8 } } ],
      'Ashen Warbrand': [ { id: 'cinderking_brand', name: "Cinderking's Brand", rolls: { atk: 27, hp: 44 } } ],
      'Voidpiercer Lance': [ { id: 'starfall_lance', name: 'Starfall Lance', rolls: { atk: 30, def: 10 } } ],
      'Godshard Edge': [ { id: 'edge_of_a_dead_god', name: 'Edge of a Dead God', rolls: { atk: 33, hp: 54 } } ],
      'Worldspine Reaver': [ { id: 'titanbane', name: 'Titanbane', rolls: { atk: 36, def: 14 } } ],
      'Veilrender Scythe': [ { id: 'last_harvest', name: 'The Last Harvest', rolls: { atk: 42, hp: 70 } } ],

      'Ironscale Hauberk': [ { id: 'scalelord_hauberk', name: "Scalelord's Hauberk", rolls: { def: 22, hp: 90 } } ],
      'Warden Plate': [ { id: 'aegis_warplate', name: 'Aegis Warplate', rolls: { def: 26, hp: 115 } } ],
      'Stormforged Cuirass': [ { id: 'thundercore_cuirass', name: 'Thundercore Cuirass', rolls: { def: 30, hp: 135, mp: 30 } } ],
      'Dragonbone Carapace': [ { id: 'wyrmscale_carapace', name: 'Wyrmscale Carapace', rolls: { def: 34, hp: 160 } } ],
      'Godshard Plate': [ { id: 'plate_of_the_fallen', name: 'Plate of the Fallen', rolls: { def: 40, hp: 195 } } ],
      'Worldspine Aegis': [ { id: 'titanheart_aegis', name: 'Titanheart Aegis', rolls: { def: 48, hp: 240 } } ],

      'Ironscale Greaves': [ { id: 'scalelord_greaves', name: "Scalelord's Greaves", rolls: { def: 17, hp: 60 } } ],
      'Warden Legplates': [ { id: 'aegis_legplates', name: 'Aegis Legplates', rolls: { def: 20, hp: 78 } } ],
      'Stormforged Tassets': [ { id: 'thundercore_tassets', name: 'Thundercore Tassets', rolls: { def: 24, hp: 100, mp: 22 } } ],
      'Dragonbone Legguards': [ { id: 'wyrmscale_legguards', name: 'Wyrmscale Legguards', rolls: { def: 28, hp: 120 } } ],
      'Godshard Legplates': [ { id: 'legplates_of_the_fallen', name: 'Legplates of the Fallen', rolls: { def: 33, hp: 150 } } ],

      'Ironshod Greaves': [ { id: 'trailbreaker_greaves', name: 'Trailbreaker Greaves', rolls: { def: 15, hp: 54 } } ],
      'Warden Sabatons': [ { id: 'aegis_sabatons', name: 'Aegis Sabatons', rolls: { def: 18, hp: 72 } } ],
      'Stormstride Boots': [ { id: 'thunderstep', name: 'Thunderstep', rolls: { def: 21, hp: 90, mp: 20 } } ],
      'Dragonbone Treads': [ { id: 'wyrmscale_treads', name: 'Wyrmscale Treads', rolls: { def: 24, hp: 112 } } ],
      'Godshard Striders': [ { id: 'striders_of_the_fallen', name: 'Striders of the Fallen', rolls: { def: 29, hp: 138 } } ],

      'Tower Shield': [ { id: 'bulwark_tower', name: 'Bastion Tower Shield', rolls: { def: 18, hp: 64 } } ],
      'Aether Codex': [ { id: 'codex_of_storms', name: 'Codex of Storms', rolls: { atk: 10, mp: 78 } } ],
      'Bulwark Shield': [ { id: 'unbreaking_bulwark', name: 'Unbreaking Bulwark', rolls: { def: 22, hp: 86 } } ],
      'Tempest Sigil': [ { id: 'eye_of_the_storm', name: 'Eye of the Storm', rolls: { atk: 13, mp: 104 } } ],
      'Dragonbone Bulwark': [ { id: 'wyrmguard_bulwark', name: 'Wyrmguard Bulwark', rolls: { def: 27, hp: 110 } } ],
      'Godshard Ward': [ { id: 'ward_of_the_fallen', name: 'Ward of the Fallen', rolls: { def: 33, hp: 135, mp: 52 } } ],

      'Bloodforged Charm': [ { id: 'heart_of_carnage', name: 'Heart of Carnage', rolls: { atk: 7, hp: 36 } } ],
      'Wardstone Amulet': [ { id: 'unyielding_wardstone', name: 'Unyielding Wardstone', rolls: { def: 8, hp: 46 } } ],
      'Arcane Lodestone': [ { id: 'singularity_stone', name: 'Singularity Stone', rolls: { atk: 6, mp: 70 } } ],
      'Godshard Talisman': [ { id: 'talisman_of_the_fallen', name: 'Talisman of the Fallen', rolls: { atk: 10, def: 10, hp: 70 } } ]
    } as const

export const CONTAINER_ITEMS = {
      'Worn Pouch': { slots: 10, cost: 0, starter: true },
      'Small Bag': { slots: 20, cost: 250 },
      "Traveler's Pack": { slots: 30, cost: 750 },
      'Tailored Backpack': { slots: 40, cost: 1500 }
    } as const

export const RENAMED_ITEMS = {
      'Velium Spear': 'Glacite Spear'
    } as const

export const RENAMED_MOBS = {
      'Innoruuk Servant': 'Asmodean Servant',
      "Innoruuk's Servant": 'Asmodean Servant',
      'Velium Stalker': 'Glacite Stalker',
      'Ssra Acolyte': 'Sythara Acolyte',
      'Shissar Inquisitor': 'Serathi Inquisitor',
      'Anguish Torturer': 'Wretchmaw Torturer',
      'Highpass Bandit': 'Cragpass Bandit',
      'Najena Cultist': 'Mordana Cultist'
    } as const

export const WEAPON_PROCS_EXPANSION = {
      'Hunter Spear':      { name: 'Hamstring', chance: 0.13, type: 'damage', min: 14, max: 26, weaken: 2 },
      'Warded Warblade':   { name: 'Riposte', chance: 0.13, type: 'damage', min: 18, max: 32, weaken: 2 },
      'Obsidian Cleaver':  { name: 'Obsidian Rend', chance: 0.14, type: 'damage', min: 24, max: 44, weaken: 3 },
      'Stormcaller Staff': { name: 'Chain Lightning', chance: 0.14, type: 'mana', min: 30, max: 60 },
      'Wyrmbone Greatbow': { name: 'Piercing Shot', chance: 0.13, type: 'damage', min: 34, max: 60, weaken: 3 },
      'Dread Halberd':     { name: 'Dread Sweep', chance: 0.15, type: 'damage', min: 42, max: 74, weaken: 4 },
      'Runescribed Maul':  { name: 'Glyph Detonation', chance: 0.14, type: 'mana', min: 44, max: 80 },
      'Tempest Glaive':    { name: 'Tempest Arc', chance: 0.16, type: 'damage', min: 56, max: 96, weaken: 4 },
      'Ashen Warbrand':    { name: 'Cinderburst', chance: 0.16, type: 'poison', min: 60, max: 105 },
      'Voidpiercer Lance': { name: 'Void Lance', chance: 0.17, type: 'damage', min: 78, max: 134, weaken: 5 },
      'Godshard Edge':     { name: 'Shatterlight', chance: 0.18, type: 'damage', min: 96, max: 168, weaken: 6 },
      'Worldspine Reaver': { name: 'Spinebreaker', chance: 0.18, type: 'damage', min: 120, max: 210, weaken: 7 },
      'Veilrender Scythe': { name: 'Veil Reap', chance: 0.2, type: 'damage', min: 150, max: 270, weaken: 8 }
    } as const

export const ALL_ITEM_DATA = Object.freeze({ ...ITEM_DATA, ...ITEM_DATA_EXPANSION })
export const ALL_WEAPON_PROCS = Object.freeze({ ...WEAPON_PROCS, ...WEAPON_PROCS_EXPANSION })
