// Generated from the frozen monolith by scripts/extract-legacy-static-data.mjs.
// Do not edit this file manually.

export const FRESH_QUESTS = [
        { name: 'Rat Problem', desc: 'Kill 5 Field Rats in Newbie Yard', mob: 'Field Rat', count: 5, xp: 150, gold: 20, done: false, prog: 0 },
        { name: 'Gnoll Slayer', desc: 'Kill 8 Gnoll Warriors in Howlfang Burrow', mob: 'Gnoll Warrior', count: 8, xp: 400, gold: 60, done: false, prog: 0 },
        { name: 'Thicket Pest Control', desc: 'Kill 6 Forest Wolves in Mistveil Hollow', mob: 'Forest Wolf', count: 6, xp: 700, gold: 95, done: false, prog: 0 },
        { name: 'Manor Cleansing', desc: 'Kill 6 Restless Zombies in Hollowmere Manor', mob: 'Restless Zombie', count: 6, xp: 900, gold: 120, done: false, prog: 0 },
        { name: 'Break the Ironskull Line', desc: 'Kill 8 Orc Centurions in Ironskull Keep', mob: 'Orc Centurion', count: 8, xp: 1500, gold: 190, done: false, prog: 0 },
        { name: 'Clear the Pass', desc: 'Kill 8 Cragpass Bandits in Cragpass Hold', mob: 'Cragpass Bandit', count: 8, xp: 2400, gold: 290, done: false, prog: 0 },
        { name: 'Fear Made Flesh', desc: 'Kill 7 Fear Elementals in Temple of Dread', mob: 'Fear Elemental', count: 7, xp: 3300, gold: 380, done: false, prog: 0 },
        { name: 'Shoreline Watch', desc: 'Kill 10 Dragonkin Scouts at the Lake of Shadows', mob: 'Dragonkin Scout', count: 10, xp: 4800, gold: 560, done: false, prog: 0 },
        { name: 'Crypt Quieted', desc: 'Kill 8 Crypt Knights in Forsaken Crypt', mob: 'Crypt Knight', count: 8, xp: 7600, gold: 860, done: false, prog: 0 },
        { name: "Mordana's Brood", desc: "Kill 8 Lava Drake Spawn in Mordana's Lair", mob: 'Lava Drake Spawn', count: 8, xp: 12000, gold: 1300, done: false, prog: 0 },
        { name: 'Seal the Vault', desc: 'Kill 9 Vault Reavers in Sundered Vault', mob: 'Vault Reaver', count: 9, xp: 26000, gold: 2400, done: false, prog: 0 },
        { name: 'Topple the Spire', desc: 'Kill 9 Obsidian Knights in Obsidian Spire', mob: 'Obsidian Knight', count: 9, xp: 42000, gold: 3600, done: false, prog: 0 },
        { name: 'Silence the Throne', desc: 'Kill 9 Throne Heralds in Hollow Throne', mob: 'Throne Herald', count: 9, xp: 68000, gold: 5400, done: false, prog: 0 },
        { name: 'Hunt the Shadow', desc: 'Kill 10 Umbral Stalkers in Umbral Reach', mob: 'Umbral Stalker', count: 10, xp: 110000, gold: 8100, done: false, prog: 0 },
        { name: 'Mend the Wrack', desc: 'Kill 10 Voidwrack Drifters in Voidwrack Expanse', mob: 'Voidwrack Drifter', count: 10, xp: 175000, gold: 12000, done: false, prog: 0 },
        { name: 'Quench the Cinderlands', desc: 'Kill 10 Cinder Tyrants in Pyreheart Cinderlands', mob: 'Cinder Tyrant', count: 10, xp: 280000, gold: 18000, done: false, prog: 0 },
        { name: 'Thaw the Eternity', desc: 'Kill 11 Glacial Behemoths in Frozen Eternity', mob: 'Glacial Behemoth', count: 11, xp: 440000, gold: 27000, done: false, prog: 0 },
        { name: 'Shatter the Court', desc: 'Kill 11 Broken Avatars in Court of Shattered Gods', mob: 'Broken Avatar', count: 11, xp: 700000, gold: 40000, done: false, prog: 0 },
        { name: 'Climb the Worldspine', desc: 'Kill 11 Titan-Bone Reavers in Worldspine Crags', mob: 'Titan-Bone Reaver', count: 11, xp: 1100000, gold: 60000, done: false, prog: 0 },
        { name: 'Drown the Necrotide', desc: 'Kill 12 Drowned Liches in Necrotide Abyss', mob: 'Drowned Lich', count: 12, xp: 1700000, gold: 90000, done: false, prog: 0 },
        { name: 'Burn the Aetherwastes', desc: 'Kill 12 Aetherburn Marauders in Aetherburn Wastes', mob: 'Aetherburn Marauder', count: 12, xp: 2600000, gold: 130000, done: false, prog: 0 },
        { name: 'Close the Maw', desc: 'Kill 12 Maw-Tongue Horrors in Maw of the Worldend', mob: 'Maw-Tongue Horror', count: 12, xp: 4000000, gold: 190000, done: false, prog: 0 },
        { name: 'Bind the Skyswound', desc: 'Kill 13 Constellation Reavers in Star-Bleeding Spire', mob: 'Constellation Reaver', count: 13, xp: 6000000, gold: 270000, done: false, prog: 0 },
        { name: 'Survive the Crucible', desc: 'Kill 13 Apotheosis Tyrants in Crucible of Apotheosis', mob: 'Apotheosis Tyrant', count: 13, xp: 9000000, gold: 400000, done: false, prog: 0 },
        { name: 'Unseat the Sovereign', desc: 'Kill 13 Timeless Sovereigns at the Throne Beyond Time', mob: 'Timeless Sovereign', count: 13, xp: 14000000, gold: 580000, done: false, prog: 0 },
        { name: 'Tear the Final Veil', desc: 'Kill 14 Veil-Renders in The Final Veil', mob: 'Veil-Render', count: 14, xp: 22000000, gold: 850000, done: false, prog: 0 }
      ] as const
