// Generated from the frozen monolith by scripts/extract-legacy-static-data.mjs.
// Do not edit this file manually.

export const RUNE_DATA = {
      'Rune: El': { id: 'El', stat: 'atk', value: 3, tier: 1 },
      'Rune: Tir': { id: 'Tir', stat: 'mp', value: 14, tier: 1 },
      'Rune: Tal': { id: 'Tal', stat: 'def', value: 3, tier: 2 },
      'Rune: Ort': { id: 'Ort', stat: 'hp', value: 24, tier: 2 },
      'Rune: Sol': { id: 'Sol', stat: 'atk', value: 6, tier: 3 },
      'Rune: Dol': { id: 'Dol', stat: 'hp', value: 38, tier: 3 },
      'Rune: Kor': { id: 'Kor', stat: 'atk', value: 10, tier: 4 },
      'Rune: Bron': { id: 'Bron', stat: 'def', value: 9, tier: 4 },
      'Rune: Lyr': { id: 'Lyr', stat: 'mp', value: 56, tier: 4 },
      'Rune: Vald': { id: 'Vald', stat: 'hp', value: 70, tier: 5 },
      'Rune: Zhar': { id: 'Zhar', stat: 'atk', value: 15, tier: 5 },
      'Rune: Morr': { id: 'Morr', stat: 'def', value: 15, tier: 6 }
    } as const

export const RUNEWORD_RECIPES_BY_SLOT = {
      weapon: [
        { runes: ['Rune: El', 'Rune: Tir'],   name: 'Runeword: Steel',         bonus: { atk: 12, mp: 20 } },
        { runes: ['Rune: El', 'Rune: Sol'],   name: 'Runeword: Bloodfang',     bonus: { atk: 8,  lifesteal: 0.05 } },
        { runes: ['Rune: El', 'Rune: Tal'],   name: 'Runeword: Tempo',         bonus: { atk: 9,  crit: 0.04 } },
        { runes: ['Rune: Tir', 'Rune: Sol'],  name: 'Runeword: Sparkspine',    bonus: { atk: 8,  mp: 44 } },
        { runes: ['Rune: Sol', 'Rune: Kor'],  name: 'Runeword: Plunder',       bonus: { atk: 14, goldFind: 0.20 } },
        { runes: ['Rune: Tal', 'Rune: Bron'], name: 'Runeword: Crusher',       bonus: { atk: 12, def: 14 } },
        { runes: ['Rune: Tir', 'Rune: Zhar'], name: "Runeword: Hunter's Mark", bonus: { atk: 16, crit: 0.05, xpFind: 0.15 } },
        { runes: ['Rune: Zhar', 'Rune: Morr'],name: 'Runeword: Wyrmpierce',    bonus: { atk: 28, def: 14, crit: 0.06 } },
      ],
      chest: [
        { runes: ['Rune: Tal', 'Rune: Ort'],  name: 'Runeword: Bulwark',    bonus: { def: 10, hp: 60 } },
        { runes: ['Rune: Tir', 'Rune: Lyr'],  name: 'Runeword: Mana Weave', bonus: { mp: 90,  xpFind: 0.15 } },
        { runes: ['Rune: Tal', 'Rune: Ort'],  name: 'Runeword: Warden',     bonus: { def: 8,  hp: 55 } },
        { runes: ['Rune: Ort', 'Rune: Bron'], name: 'Runeword: Aegis',      bonus: { def: 14, hp: 80, lifesteal: 0.04 } },
        { runes: ['Rune: Lyr', 'Rune: Vald'], name: 'Runeword: Frostheart', bonus: { mp: 80,  hp: 90 } },
        { runes: ['Rune: Vald', 'Rune: Morr'],name: 'Runeword: Dreadplate', bonus: { def: 26, hp: 150, lifesteal: 0.06 } },
      ],
      offhand: [
        { runes: ['Rune: Tal', 'Rune: Vald'], name: 'Runeword: Sanctuary',   bonus: { def: 16, hp: 110 } },
        { runes: ['Rune: Tir', 'Rune: Sol'],  name: 'Runeword: Stormcaller', bonus: { atk: 10, mp: 60,  crit: 0.04 } },
        { runes: ['Rune: Ort', 'Rune: Bron'], name: 'Runeword: Bonewall',    bonus: { def: 14, hp: 70,  goldFind: 0.15 } },
        { runes: ['Rune: Sol', 'Rune: Lyr'],  name: 'Runeword: Loremaster',  bonus: { atk: 8,  mp: 70,  xpFind: 0.20 } },
      ],
      legs: [
        { runes: ['Rune: El', 'Rune: Ort'],   name: 'Runeword: Strider',    bonus: { def: 8,  hp: 40 } },
        { runes: ['Rune: Tal', 'Rune: Sol'],  name: 'Runeword: Ironleg',    bonus: { def: 12, hp: 55 } },
        { runes: ['Rune: Bron', 'Rune: Vald'],name: 'Runeword: Stonewall',  bonus: { def: 18, hp: 80, lifesteal: 0.03 } },
      ],
      feet: [
        { runes: ['Rune: El', 'Rune: Tir'],   name: 'Runeword: Swiftfoot',  bonus: { def: 5,  hp: 24, crit: 0.03 } },
        { runes: ['Rune: Sol', 'Rune: Dol'],  name: 'Runeword: Pathfinder', bonus: { def: 8,  hp: 36, goldFind: 0.10 } },
        { runes: ['Rune: Lyr', 'Rune: Zhar'], name: 'Runeword: Windwalker', bonus: { def: 10, hp: 48, xpFind: 0.12 } },
      ],
    } as const

export const RUNEWORD_EVOLUTION_THRESHOLDS = [0, 220, 560, 1040, 1720] as const

export const RUNEWORD_EVOLUTION_MULT_PER_TIER = 0.2 as const

export const RUNE_TRANSMUTE_CHAIN = ['Rune: El', 'Rune: Tir', 'Rune: Tal', 'Rune: Ort', 'Rune: Sol', 'Rune: Dol', 'Rune: Kor', 'Rune: Bron', 'Rune: Lyr', 'Rune: Vald', 'Rune: Zhar', 'Rune: Morr'] as const

export const SHOP_BASE_PRICES = {
      hpMinor: 50,
      mpMinor: 50,
      hpLight: 500,
      mpLight: 500,
      hpGreater: 1400,
      mpGreater: 1400,
      hpSuperior: 4500,
      mpSuperior: 4500,
      hpHeroic: 11000,
      mpHeroic: 11000,
      hpEpic: 24000,
      mpEpic: 24000,
      hpLegendary: 55000,
      mpLegendary: 55000,
      steelLongsword: 40,
      knightChestplate: 55,
      occultistReforge: 80,
      occultistSocket: 65,
      nameChangeToken: 25000,
      raceChangeToken: 100000,
      appearanceChangeToken: 5000
    } as const

export const MAX_SHOP_SELLBACK_RATE = 0.5 as const
