// Generated from the frozen monolith by scripts/extract-legacy-static-data.mjs.
// Do not edit this file manually.

export const SPELLBOOK_BY_CLASS = {
      Warrior: [
        { id: 'shield_slam', name: 'Shield Slam', mp: 20, cooldown: 9, levelReq: 1, cost: 0, desc: 'Heavy blow that weakens enemy ATK.', target: 'enemy', kind: 'damage_weaken', power: 2.1, variance: 12, weaken: 2 },
        { id: 'taunting_blow', name: 'Taunting Blow', mp: 14, cooldown: 6, levelReq: 4, cost: 40, desc: 'Reliable melee strike.', target: 'enemy', kind: 'damage', power: 1.6, variance: 8 },
        { id: 'second_wind', name: 'Second Wind', mp: 18, cooldown: 14, levelReq: 8, cost: 110, desc: 'Battle recovery for HP.', target: 'self', kind: 'heal', healPct: 0.3, variance: 10 },
        { id: 'war_iron_breaker', name: 'Iron Breaker', mp: 24, cooldown: 11, levelReq: 12, cost: 185, desc: 'Crushing strike that heavily weakens the target.', target: 'enemy', kind: 'damage_weaken', power: 2.7, variance: 14, weaken: 4 },
        { id: 'war_colossus_strike', name: 'Colossus Strike', mp: 30, cooldown: 10, levelReq: 16, cost: 260, desc: 'A massive weapon blow with brutal impact.', target: 'enemy', kind: 'damage', power: 3.3, variance: 16 },
        { id: 'war_last_stand', name: 'Last Stand', mp: 24, cooldown: 16, levelReq: 20, cost: 360, desc: 'Battle-forged resolve restores heavy health.', target: 'self', kind: 'heal', healPct: 0.44, variance: 12 }
      ],
      Cleric: [
        { id: 'holy_bolt', name: 'Holy Bolt', mp: 18, cooldown: 6, levelReq: 1, cost: 0, desc: 'Divine ranged damage.', target: 'enemy', kind: 'damage', power: 1.9, variance: 10 },
        { id: 'greater_heal', name: 'Greater Heal', mp: 30, cooldown: 14, levelReq: 5, cost: 65, desc: 'Large restorative prayer.', target: 'self', kind: 'heal', healPct: 0.5, variance: 12 },
        { id: 'benediction', name: 'Benediction', mp: 22, cooldown: 16, levelReq: 9, cost: 120, desc: 'Restores mana through devotion.', target: 'self', kind: 'mana', manaPct: 0.28, variance: 8 },
        { id: 'clr_sanctuary', name: 'Sanctuary', mp: 30, cooldown: 13, levelReq: 12, cost: 185, desc: 'A radiant prayer that restores a large amount of health.', target: 'self', kind: 'heal', healPct: 0.62, variance: 14 },
        { id: 'clr_holy_lance', name: 'Holy Lance', mp: 30, cooldown: 10, levelReq: 16, cost: 260, desc: 'A concentrated spear of divine judgment.', target: 'enemy', kind: 'damage', power: 3.1, variance: 15 },
        { id: 'clr_divine_reserve', name: 'Divine Reserve', mp: 20, cooldown: 15, levelReq: 20, cost: 360, desc: 'A blessing that replenishes deep mana reserves.', target: 'self', kind: 'mana', manaPct: 0.48, variance: 12 }
      ],
      Paladin: [
        { id: 'pal_holy_strike', name: 'Holy Strike', mp: 20, cooldown: 8, levelReq: 1, cost: 0, desc: 'Sanctified weapon strike.', target: 'enemy', kind: 'damage', power: 2.0, variance: 11 },
        { id: 'pal_lay_hands', name: 'Lay on Hands', mp: 30, cooldown: 16, levelReq: 5, cost: 70, desc: 'Strong emergency heal.', target: 'self', kind: 'heal', healPct: 0.45, variance: 10 },
        { id: 'pal_aegis', name: 'Aegis of Light', mp: 24, cooldown: 12, levelReq: 9, cost: 130, desc: 'Smite and weaken enemy offense.', target: 'enemy', kind: 'damage_weaken', power: 1.8, variance: 9, weaken: 3 },
        { id: 'pal_zeal_judgment', name: 'Zeal Judgment', mp: 28, cooldown: 11, levelReq: 12, cost: 185, desc: 'Holy verdict that deals heavy damage.', target: 'enemy', kind: 'damage', power: 2.9, variance: 16 },
        { id: 'pal_vindicator', name: 'Vindicator', mp: 30, cooldown: 10, levelReq: 16, cost: 260, desc: 'A righteous strike that shatters enemy offense.', target: 'enemy', kind: 'damage_weaken', power: 3.1, variance: 15, weaken: 4 },
        { id: 'pal_sacred_vigor', name: 'Sacred Vigor', mp: 24, cooldown: 15, levelReq: 20, cost: 360, desc: 'Divine vigor surges through your body.', target: 'self', kind: 'heal', healPct: 0.5, variance: 12 }
      ],
      Ranger: [
        { id: 'rng_double_shot', name: 'Double Shot', mp: 16, cooldown: 7, levelReq: 1, cost: 0, desc: 'Two rapid ranged strikes.', target: 'enemy', kind: 'damage', power: 2.2, variance: 12 },
        { id: 'rng_vine_snare', name: 'Vine Snare', mp: 20, cooldown: 10, levelReq: 4, cost: 55, desc: 'Nature shot that hinders attacks.', target: 'enemy', kind: 'damage_weaken', power: 1.7, variance: 8, weaken: 2 },
        { id: 'rng_field_dress', name: 'Field Dress', mp: 18, cooldown: 13, levelReq: 8, cost: 110, desc: 'Quick wilderness recovery.', target: 'self', kind: 'heal', healPct: 0.28, variance: 9 },
        { id: 'rng_falcon_barrage', name: 'Falcon Barrage', mp: 24, cooldown: 10, levelReq: 12, cost: 185, desc: 'A storm of arrows tears through the enemy.', target: 'enemy', kind: 'damage', power: 2.8, variance: 15 },
        { id: 'rng_predator_volley', name: 'Predator Volley', mp: 28, cooldown: 9, levelReq: 16, cost: 260, desc: 'A lethal burst of precision shots.', target: 'enemy', kind: 'damage', power: 3.2, variance: 16 },
        { id: 'rng_natures_refuge', name: "Nature's Refuge", mp: 22, cooldown: 14, levelReq: 20, cost: 360, desc: 'Wild growth mends wounds in moments.', target: 'self', kind: 'heal', healPct: 0.43, variance: 11 }
      ],
      'Death Knight': [
        { id: 'sk_drain_strike', name: 'Drain Strike', mp: 22, cooldown: 8, levelReq: 1, cost: 0, desc: 'Unholy hit that restores life.', target: 'enemy', kind: 'damage', power: 2.1, variance: 11 },
        { id: 'sk_disease_touch', name: 'Disease Touch', mp: 24, cooldown: 11, levelReq: 5, cost: 65, desc: 'Cursed blade with poison follow-up.', target: 'enemy', kind: 'damage_poison', power: 2.3, variance: 10, poisonMin: 8, poisonMax: 16 },
        { id: 'sk_grim_guard', name: 'Grim Guard', mp: 20, cooldown: 12, levelReq: 9, cost: 125, desc: 'Dark blow that weakens the foe.', target: 'enemy', kind: 'damage_weaken', power: 1.9, variance: 9, weaken: 3 },
        { id: 'sk_nightfall_brand', name: 'Nightfall Brand', mp: 28, cooldown: 11, levelReq: 12, cost: 185, desc: 'Unholy brand that inflicts heavy poison damage.', target: 'enemy', kind: 'damage_poison', power: 2.7, variance: 13, poisonMin: 12, poisonMax: 22 },
        { id: 'sk_abyssal_reap', name: 'Abyssal Reap', mp: 32, cooldown: 10, levelReq: 16, cost: 260, desc: 'A dread slash infused with abyssal rot.', target: 'enemy', kind: 'damage_poison', power: 3.1, variance: 15, poisonMin: 14, poisonMax: 24 },
        { id: 'sk_blood_pact', name: 'Blood Pact', mp: 24, cooldown: 15, levelReq: 20, cost: 360, desc: 'Dark power siphons life back to you.', target: 'self', kind: 'heal', healPct: 0.46, variance: 12 }
      ],
      Druid: [
        { id: 'dru_solar_wrath', name: 'Solar Wrath', mp: 20, cooldown: 7, levelReq: 1, cost: 0, desc: 'Nature-fueled spell damage.', target: 'enemy', kind: 'damage', power: 2.0, variance: 11 },
        { id: 'dru_regrowth', name: 'Regrowth', mp: 24, cooldown: 13, levelReq: 5, cost: 60, desc: 'Steady healing from nature.', target: 'self', kind: 'heal', healPct: 0.34, variance: 10 },
        { id: 'dru_spirit_tap', name: 'Spirit Tap', mp: 16, cooldown: 12, levelReq: 8, cost: 115, desc: 'Draws mana from natural currents.', target: 'self', kind: 'mana', manaPct: 0.32, variance: 9 },
        { id: 'dru_stormthorn', name: 'Stormthorn', mp: 26, cooldown: 10, levelReq: 12, cost: 185, desc: 'Nature wrath lashes the enemy and saps strength.', target: 'enemy', kind: 'damage_weaken', power: 2.5, variance: 12, weaken: 3 },
        { id: 'dru_solar_tempest', name: 'Solar Tempest', mp: 30, cooldown: 10, levelReq: 16, cost: 260, desc: 'A radiant storm scorches your foe.', target: 'enemy', kind: 'damage', power: 3.2, variance: 17 },
        { id: 'dru_verdant_well', name: 'Verdant Well', mp: 22, cooldown: 14, levelReq: 20, cost: 360, desc: 'Nature spirits refill your mana flow.', target: 'self', kind: 'mana', manaPct: 0.46, variance: 11 }
      ],
      Monk: [
        { id: 'mnk_tiger_claw', name: 'Tiger Claw', mp: 16, cooldown: 6, levelReq: 1, cost: 0, desc: 'Disciplined crushing strike.', target: 'enemy', kind: 'damage', power: 2.4, variance: 12 },
        { id: 'mnk_stunning_palm', name: 'Stunning Palm', mp: 18, cooldown: 9, levelReq: 4, cost: 50, desc: 'Palm strike that weakens response.', target: 'enemy', kind: 'damage_weaken', power: 1.8, variance: 8, weaken: 2 },
        { id: 'mnk_centering', name: 'Centering', mp: 14, cooldown: 12, levelReq: 8, cost: 100, desc: 'Inner focus restores vitality.', target: 'self', kind: 'heal', healPct: 0.27, variance: 8 },
        { id: 'mnk_quivering_palm', name: 'Quivering Palm', mp: 22, cooldown: 10, levelReq: 12, cost: 185, desc: 'A devastating strike with disciplined force.', target: 'enemy', kind: 'damage', power: 3.0, variance: 14 },
        { id: 'mnk_hundred_fists', name: 'Hundred Fists', mp: 26, cooldown: 9, levelReq: 16, cost: 260, desc: 'A flurry of blindingly fast strikes.', target: 'enemy', kind: 'damage', power: 3.3, variance: 15 },
        { id: 'mnk_zen_breath', name: 'Zen Breath', mp: 18, cooldown: 14, levelReq: 20, cost: 360, desc: 'Inner discipline restores body and mind.', target: 'self', kind: 'heal', healPct: 0.4, variance: 10 }
      ],
      Bard: [
        { id: 'brd_sonic_slash', name: 'Sonic Slash', mp: 18, cooldown: 7, levelReq: 1, cost: 0, desc: 'Blade strike driven by song.', target: 'enemy', kind: 'damage', power: 1.9, variance: 10 },
        { id: 'brd_harmony', name: 'Harmony Verse', mp: 16, cooldown: 11, levelReq: 4, cost: 55, desc: 'Restorative tune for HP.', target: 'self', kind: 'heal', healPct: 0.08, variance: 8 },
        { id: 'brd_mana_ballad', name: 'Mana Ballad', mp: 16, cooldown: 13, levelReq: 8, cost: 105, desc: 'Song that replenishes mana.', target: 'self', kind: 'mana', manaPct: 0.3, variance: 8 },
        { id: 'brd_dirge_breaker', name: 'Dirge Breaker', mp: 24, cooldown: 11, levelReq: 12, cost: 185, desc: 'A war chant that damages and rattles the foe.', target: 'enemy', kind: 'damage_weaken', power: 2.4, variance: 12, weaken: 3 },
        { id: 'brd_resonant_crescendo', name: 'Resonant Crescendo', mp: 28, cooldown: 10, levelReq: 16, cost: 260, desc: 'A rising chorus batters enemy defenses.', target: 'enemy', kind: 'damage_weaken', power: 2.9, variance: 14, weaken: 4 },
        { id: 'brd_majors_refrain', name: "Major's Refrain", mp: 20, cooldown: 14, levelReq: 20, cost: 360, desc: 'An uplifting verse restores mana quickly.', target: 'self', kind: 'mana', manaPct: 0.44, variance: 10 }
      ],
      Wizard: [
        { id: 'fireball', name: 'Fireball', mp: 26, cooldown: 8, levelReq: 1, cost: 0, desc: 'Focused burst of fire.', target: 'enemy', kind: 'damage', power: 2.8, variance: 18 },
        { id: 'ice_comet', name: 'Ice Comet', mp: 42, cooldown: 16, levelReq: 7, cost: 95, desc: 'Massive long-cast nuke.', target: 'enemy', kind: 'damage', power: 4.3, variance: 28 },
        { id: 'clarity', name: 'Clarity', mp: 14, cooldown: 12, levelReq: 4, cost: 50, desc: 'Converts focus into mana.', target: 'self', kind: 'mana', manaPct: 0.35, variance: 10 },
        { id: 'wiz_chain_lightning', name: 'Chain Lightning', mp: 36, cooldown: 12, levelReq: 12, cost: 185, desc: 'Explosive arcane lightning strike.', target: 'enemy', kind: 'damage', power: 3.7, variance: 22 },
        { id: 'wiz_starfire', name: 'Starfire', mp: 42, cooldown: 11, levelReq: 16, cost: 260, desc: 'A star-hot blast engulfs the target.', target: 'enemy', kind: 'damage', power: 4.1, variance: 24 },
        { id: 'wiz_arcane_well', name: 'Arcane Well', mp: 18, cooldown: 15, levelReq: 20, cost: 360, desc: 'Pure arcana rapidly replenishes mana.', target: 'self', kind: 'mana', manaPct: 0.5, variance: 12 }
      ],
      Conjurer: [
        { id: 'mag_flame_orb', name: 'Flame Orb', mp: 24, cooldown: 8, levelReq: 1, cost: 0, desc: 'Summoned orb detonates on impact.', target: 'enemy', kind: 'damage', power: 2.5, variance: 14 },
        { id: 'mag_shock_lance', name: 'Shock Lance', mp: 28, cooldown: 11, levelReq: 5, cost: 75, desc: 'Elemental lance with heavy burst.', target: 'enemy', kind: 'damage', power: 3.1, variance: 18 },
        { id: 'mag_essence_draw', name: 'Essence Draw', mp: 16, cooldown: 12, levelReq: 9, cost: 130, desc: 'Arcane conversion restores mana.', target: 'self', kind: 'mana', manaPct: 0.34, variance: 9 },
        { id: 'mag_prismatic_lance', name: 'Prismatic Lance', mp: 32, cooldown: 11, levelReq: 12, cost: 185, desc: 'Concentrated elemental beam of destructive force.', target: 'enemy', kind: 'damage', power: 3.4, variance: 19 },
        { id: 'mag_ether_nova', name: 'Ether Nova', mp: 38, cooldown: 10, levelReq: 16, cost: 260, desc: 'A volatile elemental nova detonates on impact.', target: 'enemy', kind: 'damage', power: 3.9, variance: 22 },
        { id: 'mag_planar_siphon', name: 'Planar Siphon', mp: 18, cooldown: 14, levelReq: 20, cost: 360, desc: 'Draws deep mana from planar currents.', target: 'self', kind: 'mana', manaPct: 0.47, variance: 11 }
      ],
      Enchanter: [
        { id: 'enc_mind_spike', name: 'Mind Spike', mp: 20, cooldown: 7, levelReq: 1, cost: 0, desc: 'Psychic damage attack.', target: 'enemy', kind: 'damage', power: 2.1, variance: 12 },
        { id: 'enc_daze', name: 'Daze', mp: 18, cooldown: 10, levelReq: 4, cost: 55, desc: 'Mental shock weakens enemy attacks.', target: 'enemy', kind: 'damage_weaken', power: 1.7, variance: 8, weaken: 3 },
        { id: 'enc_gift_of_mind', name: 'Gift of Mind', mp: 14, cooldown: 12, levelReq: 8, cost: 115, desc: 'Harnessed focus restores mana.', target: 'self', kind: 'mana', manaPct: 0.36, variance: 10 },
        { id: 'enc_psychic_lance', name: 'Psychic Lance', mp: 24, cooldown: 10, levelReq: 12, cost: 185, desc: 'A mental spear that breaks enemy resolve.', target: 'enemy', kind: 'damage_weaken', power: 2.5, variance: 12, weaken: 4 },
        { id: 'enc_ego_shatter', name: 'Ego Shatter', mp: 30, cooldown: 10, levelReq: 16, cost: 260, desc: 'Shatters the enemy mind with focused force.', target: 'enemy', kind: 'damage_weaken', power: 3.0, variance: 14, weaken: 5 },
        { id: 'enc_mind_spring', name: 'Mind Spring', mp: 18, cooldown: 14, levelReq: 20, cost: 360, desc: 'A deep meditative pulse restores mana.', target: 'self', kind: 'mana', manaPct: 0.48, variance: 11 }
      ],
      Shaman: [
        { id: 'shm_spirit_spear', name: 'Spirit Spear', mp: 18, cooldown: 7, levelReq: 1, cost: 0, desc: 'Totemic force strikes the enemy.', target: 'enemy', kind: 'damage', power: 2.0, variance: 11 },
        { id: 'shm_fetid_bite', name: 'Fetid Bite', mp: 22, cooldown: 10, levelReq: 4, cost: 60, desc: 'Venom curse applies poison.', target: 'enemy', kind: 'damage_poison', power: 2.1, variance: 10, poisonMin: 7, poisonMax: 16 },
        { id: 'shm_ancestral_mend', name: 'Ancestral Mend', mp: 20, cooldown: 13, levelReq: 8, cost: 110, desc: 'Calls spirits for healing.', target: 'self', kind: 'heal', healPct: 0.33, variance: 10 },
        { id: 'shm_hexstorm', name: 'Hexstorm', mp: 28, cooldown: 11, levelReq: 12, cost: 185, desc: 'A storm of curses and venom tears at the enemy.', target: 'enemy', kind: 'damage_poison', power: 2.6, variance: 13, poisonMin: 11, poisonMax: 21 },
        { id: 'shm_totem_blight', name: 'Totem Blight', mp: 32, cooldown: 10, levelReq: 16, cost: 260, desc: 'A malignant totem curse ravages the foe.', target: 'enemy', kind: 'damage_poison', power: 3.0, variance: 15, poisonMin: 13, poisonMax: 24 },
        { id: 'shm_ancestral_tide', name: 'Ancestral Tide', mp: 22, cooldown: 14, levelReq: 20, cost: 360, desc: 'Spirits surge to restore major health.', target: 'self', kind: 'heal', healPct: 0.47, variance: 12 }
      ],
      Necromancer: [
        { id: 'nec_bone_shard', name: 'Bone Shard', mp: 22, cooldown: 8, levelReq: 1, cost: 0, desc: 'Dark shard tears into the enemy.', target: 'enemy', kind: 'damage', power: 2.4, variance: 13 },
        { id: 'nec_plague_touch', name: 'Plague Touch', mp: 24, cooldown: 11, levelReq: 5, cost: 70, desc: 'Disease-infused strike with poison ticks.', target: 'enemy', kind: 'damage_poison', power: 2.2, variance: 10, poisonMin: 9, poisonMax: 19 },
        { id: 'nec_life_tap', name: 'Life Tap', mp: 18, cooldown: 12, levelReq: 9, cost: 125, desc: 'Steals life to heal the caster.', target: 'self', kind: 'heal', healPct: 0.3, variance: 9 },
        { id: 'nec_grave_burst', name: 'Grave Burst', mp: 30, cooldown: 11, levelReq: 12, cost: 185, desc: 'An eruption of grave rot devastates the target.', target: 'enemy', kind: 'damage_poison', power: 2.8, variance: 14, poisonMin: 12, poisonMax: 24 },
        { id: 'nec_marrow_blight', name: 'Marrow Blight', mp: 34, cooldown: 10, levelReq: 16, cost: 260, desc: 'A soul-sickening plague consumes the enemy.', target: 'enemy', kind: 'damage_poison', power: 3.2, variance: 16, poisonMin: 15, poisonMax: 26 },
        { id: 'nec_soul_feast', name: 'Soul Feast', mp: 22, cooldown: 14, levelReq: 20, cost: 360, desc: 'Devours lingering essence to restore health.', target: 'self', kind: 'heal', healPct: 0.48, variance: 12 }
      ],
      Rogue: [
        { id: 'backstab', name: 'Backstab', mp: 20, cooldown: 7, levelReq: 1, cost: 0, desc: 'High burst precision strike.', target: 'enemy', kind: 'damage', power: 3.0, variance: 16 },
        { id: 'poison_strike', name: 'Poison Strike', mp: 24, cooldown: 10, levelReq: 5, cost: 70, desc: 'Strike plus poison follow-up chance.', target: 'enemy', kind: 'damage_poison', power: 2.6, variance: 12, poisonMin: 8, poisonMax: 18 },
        { id: 'shadow_mend', name: 'Shadow Mend', mp: 16, cooldown: 13, levelReq: 8, cost: 105, desc: 'Recover while staying elusive.', target: 'self', kind: 'heal', healPct: 0.26, variance: 9 },
        { id: 'rog_heartseeker', name: 'Heartseeker', mp: 24, cooldown: 10, levelReq: 12, cost: 185, desc: 'A lethal precision strike from the shadows.', target: 'enemy', kind: 'damage', power: 3.4, variance: 17 },
        { id: 'rog_eviscerate', name: 'Eviscerate', mp: 28, cooldown: 9, levelReq: 16, cost: 260, desc: 'A vicious finishing strike tears through armor.', target: 'enemy', kind: 'damage', power: 3.7, variance: 18 },
        { id: 'rog_smoke_recovery', name: 'Smoke Recovery', mp: 18, cooldown: 14, levelReq: 20, cost: 360, desc: 'Fade and recover while cloaked in smoke.', target: 'self', kind: 'heal', healPct: 0.42, variance: 10 }
      ],
      Beastmaster: [
        { id: 'bst_claw_fury', name: 'Claw Fury', mp: 18, cooldown: 7, levelReq: 1, cost: 0, desc: 'Primal strike from beast training.', target: 'enemy', kind: 'damage', power: 2.3, variance: 12 },
        { id: 'bst_feral_venom', name: 'Feral Venom', mp: 20, cooldown: 10, levelReq: 5, cost: 65, desc: 'Savage attack with poison.', target: 'enemy', kind: 'damage_poison', power: 2.2, variance: 10, poisonMin: 8, poisonMax: 17 },
        { id: 'bst_spirit_howl', name: 'Spirit Howl', mp: 16, cooldown: 12, levelReq: 9, cost: 120, desc: 'Primal call restores vitality.', target: 'self', kind: 'heal', healPct: 0.29, variance: 9 },
        { id: 'bst_primal_maul', name: 'Primal Maul', mp: 24, cooldown: 10, levelReq: 12, cost: 185, desc: 'Savage mauling strike empowered by wild spirits.', target: 'enemy', kind: 'damage', power: 3.0, variance: 15 },
        { id: 'bst_apex_rend', name: 'Apex Rend', mp: 28, cooldown: 9, levelReq: 16, cost: 260, desc: 'A feral tear backed by primal force.', target: 'enemy', kind: 'damage', power: 3.4, variance: 16 },
        { id: 'bst_spirit_pack', name: 'Spirit Pack', mp: 20, cooldown: 14, levelReq: 20, cost: 360, desc: 'Pack spirits mend your wounds quickly.', target: 'self', kind: 'heal', healPct: 0.45, variance: 11 }
      ],
      Berserker: [
        { id: 'brs_whirl_axe', name: 'Whirling Axe', mp: 14, cooldown: 6, levelReq: 1, cost: 0, desc: 'Axe rush for brutal damage.', target: 'enemy', kind: 'damage', power: 2.5, variance: 13 },
        { id: 'brs_bloodrage', name: 'Bloodrage', mp: 16, cooldown: 9, levelReq: 4, cost: 55, desc: 'Frenzied strike that weakens foe.', target: 'enemy', kind: 'damage_weaken', power: 2.1, variance: 9, weaken: 2 },
        { id: 'brs_war_cry', name: 'War Cry', mp: 12, cooldown: 12, levelReq: 8, cost: 100, desc: 'Battle roar restores fighting spirit.', target: 'self', kind: 'heal', healPct: 0.24, variance: 8 },
        { id: 'brs_onslaught', name: 'Onslaught', mp: 22, cooldown: 9, levelReq: 12, cost: 185, desc: 'A frenzied charge that tears through defenses.', target: 'enemy', kind: 'damage_weaken', power: 2.8, variance: 13, weaken: 3 },
        { id: 'brs_butchers_fury', name: "Butcher's Fury", mp: 26, cooldown: 8, levelReq: 16, cost: 260, desc: 'Relentless attacks crash into the target.', target: 'enemy', kind: 'damage', power: 3.5, variance: 16 },
        { id: 'brs_blood_recovery', name: 'Blood Recovery', mp: 18, cooldown: 14, levelReq: 20, cost: 360, desc: 'Rage-fueled resilience restores health.', target: 'self', kind: 'heal', healPct: 0.41, variance: 10 }
      ]
    } as const

export const CLASS_EPIC_CONTENT = {
      Warrior: {
        questName: 'Epic Trial: Steel Oath', target: 'Asmodean Servant', count: 30,
        desc: 'Defeat Asmodean Servants and forge your final oath.',
        spell: { id: 'epic_warrior_oathbreaker', name: 'Epic: Oathbreaker', mp: 40, cooldown: 12, levelReq: 1, cost: 0, epic: true, desc: 'Legendary cleave that crushes enemy guard.', target: 'enemy', kind: 'damage_weaken', power: 4.1, variance: 20, weaken: 6 }
      },
      Cleric: {
        questName: 'Epic Trial: Light Everlasting', target: 'Aegis Herald', count: 28,
        desc: 'Purge Aegis Heralds to unlock divine restoration.',
        spell: { id: 'epic_cleric_seraphim', name: 'Epic: Seraphim Grace', mp: 42, cooldown: 14, levelReq: 1, cost: 0, epic: true, desc: 'Miraculous healing beyond mortal limits.', target: 'self', kind: 'heal', healPct: 0.82, variance: 16 }
      },
      Paladin: {
        questName: 'Epic Trial: Righteous Flame', target: 'Valor Knight', count: 30,
        desc: 'Prove your valor against celestial champions.',
        spell: { id: 'epic_paladin_verdict', name: 'Epic: Final Verdict', mp: 40, cooldown: 12, levelReq: 1, cost: 0, epic: true, desc: 'Holy execution with overwhelming force.', target: 'enemy', kind: 'damage', power: 4.0, variance: 20 }
      },
      Ranger: {
        questName: 'Epic Trial: Wild Hunt', target: 'Glacite Stalker', count: 32,
        desc: 'Hunt Glacite Stalkers and master the apex shot.',
        spell: { id: 'epic_ranger_godshot', name: 'Epic: Godshot', mp: 38, cooldown: 11, levelReq: 1, cost: 0, epic: true, desc: 'An unmatched hunt shot that pierces all defenses.', target: 'enemy', kind: 'damage', power: 4.2, variance: 21 }
      },
      'Death Knight': {
        questName: 'Epic Trial: Grave Dominion', target: 'Demi-Lich', count: 26,
        desc: 'Harvest the might of Demi-Liches in dark ritual.',
        spell: { id: 'epic_shadow_knight_voidbrand', name: 'Epic: Voidbrand', mp: 42, cooldown: 12, levelReq: 1, cost: 0, epic: true, desc: 'Corrupting strike with devastating plague.', target: 'enemy', kind: 'damage_poison', power: 3.9, variance: 18, poisonMin: 22, poisonMax: 34 }
      },
      Druid: {
        questName: 'Epic Trial: Verdant Tempest', target: 'Blight Horror', count: 30,
        desc: 'Cleanse Blight Horrors to command primal storms.',
        spell: { id: 'epic_druid_worldbloom', name: 'Epic: Worldbloom', mp: 40, cooldown: 13, levelReq: 1, cost: 0, epic: true, desc: 'A worldroot surge that restores and renews mana.', target: 'self', kind: 'mana', manaPct: 0.68, variance: 15 }
      },
      Monk: {
        questName: 'Epic Trial: Perfect Form', target: 'Cyclone Champion', count: 30,
        desc: 'Defeat Cyclone Champions to complete the final kata.',
        spell: { id: 'epic_monk_thousand_palms', name: 'Epic: Thousand Palms', mp: 36, cooldown: 10, levelReq: 1, cost: 0, epic: true, desc: 'A legendary barrage of flawless strikes.', target: 'enemy', kind: 'damage', power: 4.0, variance: 19 }
      },
      Bard: {
        questName: 'Epic Trial: Anthem of Ages', target: 'Cloudbreaker Adept', count: 30,
        desc: 'Gather lost verses from Cloudbreaker Adepts.',
        spell: { id: 'epic_bard_anthem_ruin', name: 'Epic: Anthem of Ruin', mp: 38, cooldown: 12, levelReq: 1, cost: 0, epic: true, desc: 'A ruinous anthem that cripples enemy offense.', target: 'enemy', kind: 'damage_weaken', power: 3.7, variance: 17, weaken: 6 }
      },
      Wizard: {
        questName: 'Epic Trial: Starfire Codex', target: 'Magma Sentinel', count: 28,
        desc: 'Study the cores of Magma Sentinels to finish the codex.',
        spell: { id: 'epic_wizard_supernova', name: 'Epic: Supernova', mp: 52, cooldown: 14, levelReq: 1, cost: 0, epic: true, desc: 'Cataclysmic arcane detonation.', target: 'enemy', kind: 'damage', power: 4.8, variance: 28 }
      },
      Conjurer: {
        questName: 'Epic Trial: Planar Core', target: 'Ash Drake', count: 28,
        desc: 'Harvest planar embers from Ash Drakes.',
        spell: { id: 'epic_conjurer_prismatic_collapse', name: 'Epic: Prismatic Collapse', mp: 48, cooldown: 13, levelReq: 1, cost: 0, epic: true, desc: 'Elemental collapse tearing through reality.', target: 'enemy', kind: 'damage', power: 4.5, variance: 24 }
      },
      Enchanter: {
        questName: 'Epic Trial: Mind Dominion', target: 'Void Archivist', count: 26,
        desc: 'Break the will of Void Archivists.',
        spell: { id: 'epic_enchanter_neural_break', name: 'Epic: Neural Break', mp: 40, cooldown: 12, levelReq: 1, cost: 0, epic: true, desc: 'Absolute psychic rupture and suppression.', target: 'enemy', kind: 'damage_weaken', power: 3.9, variance: 18, weaken: 7 }
      },
      Shaman: {
        questName: 'Epic Trial: Spirit Pact', target: 'Poxbound Ritualist', count: 30,
        desc: 'Silence Poxbound Ritualists to secure spirit favor.',
        spell: { id: 'epic_shaman_ancestral_storm', name: 'Epic: Ancestral Storm', mp: 42, cooldown: 12, levelReq: 1, cost: 0, epic: true, desc: 'Totemic plague storm with massive poison output.', target: 'enemy', kind: 'damage_poison', power: 4.0, variance: 18, poisonMin: 20, poisonMax: 34 }
      },
      Necromancer: {
        questName: 'Epic Trial: Death Choir', target: 'Cryptflame Adept', count: 30,
        desc: 'Collect soul-echoes from Cryptflame Adepts.',
        spell: { id: 'epic_necromancer_requiem', name: 'Epic: Grave Requiem', mp: 44, cooldown: 12, levelReq: 1, cost: 0, epic: true, desc: 'A funeral hymn that rots and withers enemies.', target: 'enemy', kind: 'damage_poison', power: 4.1, variance: 19, poisonMin: 22, poisonMax: 36 }
      },
      Rogue: {
        questName: 'Epic Trial: Night Contract', target: 'Painforged Guard', count: 30,
        desc: 'Fulfill silent contracts against Painforged Guards.',
        spell: { id: 'epic_rogue_midnight_execution', name: 'Epic: Midnight Execution', mp: 36, cooldown: 9, levelReq: 1, cost: 0, epic: true, desc: 'Execution-level critical assault.', target: 'enemy', kind: 'damage', power: 4.3, variance: 22 }
      },
      Beastmaster: {
        questName: 'Epic Trial: Apex Bond', target: 'Ember Devourer', count: 30,
        desc: 'Defeat Ember Devourers to awaken the primal pact.',
        spell: { id: 'epic_beastmaster_pack_alpha', name: 'Epic: Pack Alpha', mp: 38, cooldown: 10, levelReq: 1, cost: 0, epic: true, desc: 'Alpha strike empowered by a spectral pack.', target: 'enemy', kind: 'damage', power: 4.0, variance: 20 }
      },
      Berserker: {
        questName: 'Epic Trial: Crimson End', target: 'Wretchmaw Torturer', count: 30,
        desc: 'End Wretchmaw Torturers in a whirlwind of rage.',
        spell: { id: 'epic_berserker_redline', name: 'Epic: Redline Frenzy', mp: 36, cooldown: 9, levelReq: 1, cost: 0, epic: true, desc: 'Unhinged berserker assault that breaks enemy might.', target: 'enemy', kind: 'damage_weaken', power: 4.1, variance: 20, weaken: 5 }
      }
    } as const
