// Generated from the frozen monolith by scripts/extract-legacy-static-data.mjs.
// Do not edit this file manually.

export const ZONES = [
      { name: 'Newbie Yard', desc: 'A safe area for new adventurers.', minLvl: 1, maxLvl: 4, mobs: ['Field Rat', 'Rabid Bat', 'Skeleton Pup'], xpMult: 1, goldMult: 1, rare: 'Worn Shortsword' },
      { name: 'Howlfang Burrow', desc: 'Gnoll warrens filled with danger.', minLvl: 3, maxLvl: 6, mobs: ['Gnoll Pup', 'Gnoll Warrior', 'Gnoll Shaman'], xpMult: 1.5, goldMult: 1.4, rare: 'Gnoll Fang Earring' },
      { name: 'Hollowmere Manor', desc: 'Haunted estate, undead everywhere.', minLvl: 7, maxLvl: 12, mobs: ['Restless Zombie', 'Decaying Spectre', 'Wraith'], xpMult: 2.2, goldMult: 2, rare: 'Ghoul-Touched Cloak' },
      { name: 'Temple of Dread', desc: 'Temple of Fear. Extremely deadly.', minLvl: 15, maxLvl: 21, mobs: ['Bullywug Slave', 'Fear Elemental', 'Dread Stalker'], xpMult: 4, goldMult: 3.5, rare: 'Dread Quill' },
      { name: 'Abyss of Wrath', desc: 'Realm of Asmodeus. Legendary loot.', minLvl: 30, maxLvl: 37, mobs: ['Asmodean Servant', 'Ebon Mace Wielder', 'Demi-Lich'], xpMult: 8, goldMult: 7, rare: 'Hate Infused Plate' },
      { name: 'Ravenshade Catacombs', desc: 'Vampiric nobles and cursed crypt guards.', minLvl: 34, maxLvl: 41, mobs: ['Ravenshade Thrall', 'Bloodbound Sentry', 'Crypt Warden'], xpMult: 9, goldMult: 7.6, rare: 'Mithril Ingot' },
      { name: 'Drakemoor Ruins', desc: 'Ancient citadel crawling with scaled undead.', minLvl: 38, maxLvl: 45, mobs: ['Dragonkin Reaver', 'Bone Sentinel', 'Lizardfolk Spiritcaller'], xpMult: 10.1, goldMult: 8.2, rare: 'Spider Silk' },
      { name: 'Vexgloom Labyrinth', desc: 'Frozen tunnels and predatory ice horrors.', minLvl: 42, maxLvl: 49, mobs: ['Crystal Spider', 'Frost Wisp', 'Glacite Stalker'], xpMult: 11.3, goldMult: 8.9, rare: 'Animal Pelt' },
      { name: 'Dragon Necropolis', desc: 'Ancient drakes and their eternal dead.', minLvl: 46, maxLvl: 53, mobs: ['Skeletal Wyrm', 'Necrotic Drake', 'Cryptflame Adept'], xpMult: 12.6, goldMult: 9.6, rare: 'Orc Tooth' },
      { name: 'Sythara Temple', desc: 'Alien halls ruled by serpent fanatics.', minLvl: 50, maxLvl: 57, mobs: ['Sythara Acolyte', 'Serathi Inquisitor', 'Temple Coilguard'], xpMult: 14, goldMult: 10.4, rare: 'Bone Chip' },
      { name: 'Plaguemarsh', desc: 'Pestilent marshes of rot and suffering.', minLvl: 54, maxLvl: 61, mobs: ['Plaguebearer', 'Blight Horror', 'Poxbound Ritualist'], xpMult: 15.5, goldMult: 11.3, rare: 'Giant Snake Fang' },
      { name: 'Tempest Reach', desc: 'Thunder peaks where giants wage war.', minLvl: 58, maxLvl: 65, mobs: ['Storm Giant Scout', 'Thunder Zealot', 'Cloudbreaker Adept'], xpMult: 17.1, goldMult: 12.2, rare: 'Steel Longsword' },
      { name: 'Stormspire Bastion', desc: 'Tempest forges charged with skyfire.', minLvl: 62, maxLvl: 69, mobs: ['Tempest Smith', 'Skyfire Warden', 'Cyclone Champion'], xpMult: 18.8, goldMult: 13.2, rare: 'Knight Chestplate' },
      { name: 'Festering Crypt', desc: 'Plague crypts guarded by death priests.', minLvl: 66, maxLvl: 73, mobs: ['Rot Priest', 'Moldering Abomination', 'Decay Archivist'], xpMult: 20.6, goldMult: 14.3, rare: 'Ghoul-Touched Cloak' },
      { name: 'Bastion of Valor', desc: 'Celestial battleground of honor and steel.', minLvl: 70, maxLvl: 77, mobs: ['Valor Knight', 'Aegis Herald', 'Banner Captain'], xpMult: 22.5, goldMult: 15.5, rare: 'Dread Quill' },
      { name: 'Ember Reach', desc: 'Living flame, ash storms, and infernal hosts.', minLvl: 74, maxLvl: 81, mobs: ['Cinder Fiend', 'Magma Sentinel', 'Ashen Arcanist'], xpMult: 24.5, goldMult: 16.8, rare: 'Hate Infused Plate' },
      { name: 'Wretchmaw Vestibule', desc: 'A brutal proving ground of anguish and pain.', minLvl: 78, maxLvl: 86, mobs: ['Wretchmaw Torturer', 'Painforged Guard', 'Dread Supplicant'], xpMult: 26.6, goldMult: 18.1, rare: 'Steel Longsword' },
      { name: 'Cinderhold Depths', desc: 'Molten vaults where elder drakes sleep.', minLvl: 83, maxLvl: 91, mobs: ['Ash Drake', 'Ember Devourer', 'Pyre Channeler'], xpMult: 28.8, goldMult: 19.5, rare: 'Knight Chestplate' },
      { name: 'Citadel of Eternity', desc: 'Reality-thin stronghold beyond mortal time.', minLvl: 88, maxLvl: 96, mobs: ['Chrono Warden', 'Eternal Myrmidon', 'Void Archivist'], xpMult: 31, goldMult: 21, rare: 'Hate Infused Plate' },
      { name: 'Mistveil Hollow', desc: 'Foggy halfling woods crawling with wolves and spider broods.', minLvl: 5, maxLvl: 9, mobs: ['Forest Wolf', 'Spider Hatchling', 'Thicket Brigand'], xpMult: 1.8, goldMult: 1.7, rare: 'Spider Silk' },
      { name: 'Ironskull Keep', desc: 'Orc-held fortress, walls crusted with old blood.', minLvl: 10, maxLvl: 14, mobs: ['Ironskull Legionnaire', 'Orc Centurion', 'Orc Pawn'], xpMult: 2.8, goldMult: 2.4, rare: 'Orc Tooth' },
      { name: 'Cragpass Hold', desc: 'Mountain pass overrun by bandits and grizzled brigands.', minLvl: 13, maxLvl: 17, mobs: ['Cragpass Bandit', 'Cutthroat Scout', 'Brigand Captain'], xpMult: 3.4, goldMult: 3, rare: 'Bronze Hatchet' },
      { name: 'Lake of Shadows', desc: 'Dragonkin shoreline patrols and venomous shallows.', minLvl: 18, maxLvl: 25, mobs: ['Dragonkin Scout', 'Bog Frog', 'Drowned Sentry'], xpMult: 4.8, goldMult: 4.1, rare: 'Giant Snake Fang' },
      { name: 'Forsaken Crypt', desc: 'Sunken crypt of forgotten knights and lich-priests.', minLvl: 22, maxLvl: 29, mobs: ['Forsaken Acolyte', 'Crypt Knight', 'Tomb Lurker'], xpMult: 5.7, goldMult: 4.7, rare: 'Bone Chip' },
      { name: "Mordana's Lair", desc: 'Volcanic dungeon ruled by a vengeful sorceress.', minLvl: 26, maxLvl: 33, mobs: ['Mordana Cultist', 'Lava Drake Spawn', 'Fume Wraith'], xpMult: 6.8, goldMult: 5.5, rare: 'Mithril Ingot' },
      { name: 'Sundered Vault', desc: 'A shattered planar vault where time leaks like blood.', minLvl: 95, maxLvl: 104, mobs: ['Vault Reaver', 'Sundered Acolyte', 'Riftbound Sentry'], xpMult: 33, goldMult: 22.5, rare: 'Hate Infused Plate' },
      { name: 'Obsidian Spire', desc: 'A black tower whose stones drink the light.', minLvl: 102, maxLvl: 112, mobs: ['Obsidian Knight', 'Glasshade Wraith', 'Tower Magus'], xpMult: 36, goldMult: 24, rare: 'Mithril Ingot' },
      { name: 'Hollow Throne', desc: 'A dead god\'s throne room, still warm with rage.', minLvl: 110, maxLvl: 120, mobs: ['Throne Herald', 'Hollow Champion', 'Echo of the King'], xpMult: 39, goldMult: 26, rare: 'Knight Chestplate' },
      { name: 'Umbral Reach', desc: 'A land where shadow itself has teeth.', minLvl: 118, maxLvl: 128, mobs: ['Umbral Stalker', 'Nightblood Hunter', 'Shade Inquisitor'], xpMult: 42.5, goldMult: 28, rare: 'Dread Quill' },
      { name: 'Voidwrack Expanse', desc: 'Wreckage of a world torn loose from reality.', minLvl: 126, maxLvl: 136, mobs: ['Voidwrack Drifter', 'Null Leviathan', 'Hollow Astromancer'], xpMult: 46, goldMult: 30.5, rare: 'Spider Silk' },
      { name: 'Pyreheart Cinderlands', desc: 'A continent reduced to molten glass and slag-storms.', minLvl: 134, maxLvl: 144, mobs: ['Cinder Tyrant', 'Pyreheart Magus', 'Slag Giant'], xpMult: 50, goldMult: 33, rare: 'Hate Infused Plate' },
      { name: 'Frozen Eternity', desc: 'A glacier that remembers every soul it swallowed.', minLvl: 142, maxLvl: 152, mobs: ['Eternity Frost-Lich', 'Glacial Behemoth', 'Frozen Inquisitor'], xpMult: 54, goldMult: 35.5, rare: 'Animal Pelt' },
      { name: 'Court of Shattered Gods', desc: 'A gallery of dead deities, animated by spite.', minLvl: 150, maxLvl: 162, mobs: ['Broken Avatar', 'Godshard Sentinel', 'Apostate Choir'], xpMult: 58, goldMult: 38.5, rare: 'Hate Infused Plate' },
      { name: 'Worldspine Crags', desc: 'Mountains made from the vertebrae of a slain titan.', minLvl: 160, maxLvl: 172, mobs: ['Spine-Marrow Drake', 'Titan-Bone Reaver', 'Worldspine Oracle'], xpMult: 63, goldMult: 41.5, rare: 'Knight Chestplate' },
      { name: 'Necrotide Abyss', desc: 'A sunless ocean churning with restless dead.', minLvl: 170, maxLvl: 182, mobs: ['Drowned Lich', 'Tidewraith Sovereign', 'Abyssal Maw'], xpMult: 68, goldMult: 45, rare: 'Bone Chip' },
      { name: 'Aetherburn Wastes', desc: 'Plains where magic ignited the very air to ash.', minLvl: 180, maxLvl: 192, mobs: ['Aetherburn Marauder', 'Ashlight Sorcerer', 'Wastes Devourer'], xpMult: 73, goldMult: 48.5, rare: 'Dread Quill' },
      { name: 'Maw of the Worldend', desc: 'A wound in creation that breathes and devours.', minLvl: 190, maxLvl: 202, mobs: ['Wormend Herald', 'Maw-Tongue Horror', 'Creation Devourer'], xpMult: 79, goldMult: 52, rare: 'Spider Silk' },
      { name: 'Star-Bleeding Spire', desc: 'A spire that pierces the heavens and lets them bleed.', minLvl: 200, maxLvl: 214, mobs: ['Star-Bleeding Seraph', 'Constellation Reaver', 'Skywound Archon'], xpMult: 85, goldMult: 56, rare: 'Steel Longsword' },
      { name: 'Crucible of Apotheosis', desc: 'Where mortals are unmade and remade as something worse.', minLvl: 212, maxLvl: 226, mobs: ['Apotheosis Tyrant', 'Crucible Forge-Soul', 'Ascendant Wretch'], xpMult: 92, goldMult: 60, rare: 'Mithril Ingot' },
      { name: 'Throne Beyond Time', desc: 'A throne older than time, contested by every age at once.', minLvl: 224, maxLvl: 238, mobs: ['Timeless Sovereign', 'Aeon Crusader', 'Untime Witness'], xpMult: 100, goldMult: 65, rare: 'Hate Infused Plate' },
      { name: 'The Final Veil', desc: 'The last curtain between everything and nothing.', minLvl: 236, maxLvl: 250, mobs: ['Veil-Render', 'Final Word', 'Nothingbound Avatar'], xpMult: 108, goldMult: 70, rare: 'Hate Infused Plate' }
    ] as const

export const NAMED_BY_ZONE = {
      0: ['a rabid rat king', 'a bat matriarch'],
      1: ['an enraged gnoll packlord', 'a howlfang bloodshaman'],
      2: ['a restless butler', 'a manor revenant'],
      3: ['a fearbound high priest', 'a dread warbringer'],
      4: ['a hand of Asmodeus', 'an ebon oathkeeper'],
      5: ['countess of the crypt', 'an ancient ravenshade duelist'],
      6: ['the dragonkin bone marshal', 'an lizardfolk tombseer'],
      7: ['vexglooms broodmother', 'an icebound shadeweaver'],
      8: ['an ossified wyrm-lord', 'the necropolis gravewing'],
      9: ['a sythara high oracle', 'the coiled adjudicator'],
      10: ['lord of blighted lungs', 'a plague-tide harbinger'],
      11: ['thunder fist warmaster', 'a cloud titan emissary'],
      12: ['the skyforge executioner', 'an avatar of forked lightning'],
      13: ['high prelate of rot', 'the mold sovereign'],
      14: ['ser valorshield', 'the oathbound bannerlord'],
      15: ['the pyre regent', 'an inferno herald'],
      16: ['the chainbreaker inquisitor', 'an apostle of anguish'],
      17: ['the ashen brood patriarch', 'a molten worldeater'],
      18: ['the timeless adjudicator', 'a herald of the final hour'],
      19: ['a thicket spider matron', 'the wolf-pack alpha'],
      20: ['legionnaire commander ironmaul', 'an orc warchanter'],
      21: ['the cragpass road-warden', 'a brigand kingpin'],
      22: ['an lizardfolk tide-marshal', 'the lake serpent prime'],
      23: ['the forsaken lich-knight', 'an unbound tomb-lord'],
      24: ['mordana, fume sorceress', 'the lair drake-mother'],
      25: ['the sundered timekeeper', 'an arbiter of the broken vault'],
      26: ['the obsidian regent', 'a glasshade archon'],
      27: ['the hollow king reborn', 'an echo of the throne'],
      28: ['the umbral monarch', 'a nightblood high-hunter'],
      29: ['the voidwrack tyrant', 'the null leviathan prime'],
      30: ['pyreheart, slag-tyrant', 'the cinder god-king'],
      31: ['the frost-lich of eternity', 'the glacial titan ascendant'],
      32: ['the chorus of dead gods', 'an avatar of shattered divinity'],
      33: ['the worldspine drake-lord', 'the marrow oracle prime'],
      34: ['the necrotide drowned god', 'the abyssal maw eternal'],
      35: ['the aetherburn warlord', 'the ashlight magus supreme'],
      36: ['the worldend devourer', 'the maw-tongue sovereign'],
      37: ['the star-bled herald', 'the skywound archon prime'],
      38: ['the crucible tyrant ascendant', 'the apotheosis-forge soul'],
      39: ['the timeless sovereign eternal', 'the aeon-crusader prime'],
      40: ['the final word made flesh', 'the veil-render, end of all things']
    } as const

export const NAMED_MECHANICS = [
      { id: 'enrage', name: 'Enrage', desc: 'Gains heavy ATK at low health.' },
      { id: 'venom', name: 'Venom Aura', desc: 'Hits may apply extra poison damage.' },
      { id: 'ward', name: 'Arcane Ward', desc: 'Periodically reduces incoming damage.' }
    ] as const

export const ZONE_EVENTS = [
      { id: 'calm', name: 'Calm Skies', desc: 'No unusual energies at work.', playerDamageMult: 1, spellDamageMult: 1, mobDamageMult: 1, healMult: 1, manaMult: 1, xpMult: 1, goldMult: 1, lootMult: 1 },
      { id: 'bloodmoon', name: 'Blood Moon', desc: 'Everything hits harder and rewards improve.', playerDamageMult: 1.1, spellDamageMult: 1.1, mobDamageMult: 1.25, healMult: 1, manaMult: 1, xpMult: 1.35, goldMult: 1.25, lootMult: 1.15 },
      { id: 'arcane_winds', name: 'Arcane Winds', desc: 'Spellcraft surges with unstable power.', playerDamageMult: 1, spellDamageMult: 1.28, mobDamageMult: 1, healMult: 1, manaMult: 1.25, xpMult: 1.1, goldMult: 1, lootMult: 1 },
      { id: 'sanctified_ground', name: 'Sanctified Ground', desc: 'Healing and recovery are amplified.', playerDamageMult: 1, spellDamageMult: 1, mobDamageMult: 0.95, healMult: 1.35, manaMult: 1.1, xpMult: 1.05, goldMult: 1.05, lootMult: 1 },
      { id: 'hunters_call', name: "Hunter's Call", desc: 'Hunts are swift and loot is plentiful.', playerDamageMult: 1.08, spellDamageMult: 1.05, mobDamageMult: 0.92, healMult: 1, manaMult: 1, xpMult: 1.22, goldMult: 1.15, lootMult: 1.2 }
    ] as const

export const DUNGEON_MOBS = ['Abyss Stalker', 'Void Acolyte', 'Crypt Juggernaut', 'Rune Horror', 'Nightshade Warden'] as const

export const DUNGEON_THEMES = {
      abyssal: {
        label: 'Abyssal Vault',
        desc: 'Void-touched halls where elites and rune horrors guard ancient power.',
        mobs: ['Abyss Stalker', 'Void Acolyte', 'Crypt Juggernaut', 'Rune Horror', 'Nightshade Warden'],
        essenceMult: 1
      },
      ember: {
        label: 'Ember Crucible',
        desc: 'A furnace dungeon. Enemies are fiercer, but boss caches yield more Essence.',
        mobs: ['Cinder Ravager', 'Ashbound Acolyte', 'Forge Colossus', 'Magma Horror', 'Ember Warden'],
        mobDamageMult: 1.08,
        essenceMult: 1.2
      },
      moon: {
        label: 'Moonlit Catacombs',
        desc: 'A haunted maze that favors loot hunters and named encounters.',
        mobs: ['Moonfang Stalker', 'Grave Cantor', 'Bonebound Knight', 'Nightglass Horror', 'Pale Warden'],
        lootMult: 1.12,
        essenceMult: 1.1
      }
    } as const

export const BOSS_BY_ZONE = {
      0: { name: 'Vermin Tyrant', mob: 'Field Rat', mechanic: 'enrage' },
      1: { name: 'Bog Sovereign', mob: 'Mossback Turtle', mechanic: 'venom' },
      2: { name: 'Gnoll Warlord Karruk', mob: 'Gnoll Warrior', mechanic: 'ward' },
      3: { name: 'Lich Baron Veldrin', mob: 'Restless Zombie', mechanic: 'enrage' },
      4: { name: 'Ironhand the Unbroken', mob: 'Iron Sentinel', mechanic: 'ward' },
      5: { name: 'Frostwyrm Caelirix', mob: 'Frost Wraith', mechanic: 'venom' },
      6: { name: 'Inferno Archon', mob: 'Ember Adept', mechanic: 'enrage' },
      7: { name: 'Sea Witch Marathi', mob: 'Tide Cultist', mechanic: 'ward' },
      8: { name: 'Sand King Azhar', mob: 'Dune Stalker', mechanic: 'venom' },
      9: { name: 'Void Empress', mob: 'Void Acolyte', mechanic: 'ward' },
      10: { name: 'Storm Tyrant Zephyron', mob: 'Storm Caller', mechanic: 'enrage' },
      11: { name: 'Plague Lord Sythris', mob: 'Plague Bearer', mechanic: 'venom' },
      12: { name: 'Crimson Magister', mob: 'Crimson Cultist', mechanic: 'ward' },
      13: { name: 'Star Devourer', mob: 'Star Reaver', mechanic: 'enrage' },
      14: { name: 'Bone Emperor', mob: 'Bone Lord', mechanic: 'ward' },
      15: { name: 'Dread Behemoth', mob: 'Dread Hulk', mechanic: 'enrage' },
      16: { name: 'Hollow Sovereign', mob: 'Hollow Knight', mechanic: 'venom' },
      17: { name: 'Twilight Sovereign', mob: 'Twilight Drake', mechanic: 'ward' },
      18: { name: 'World-Ender', mob: 'Apocalypse Herald', mechanic: 'enrage' }
    } as const
